//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::paging::cursor_or_done;
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, PaginatedResponse, Result,
};

use crate::meta::DefaultMeta;
use crate::types::ProfileView;

/// Whose follows and which page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
    pub actor: String,
    /// Rows per page. Range [1, 100]; defaults to 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Opaque page token from the previous response; omit for the first page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One page of follows.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Follows {
    pub subject: ProfileView,
    /// Token for the next page; absent on the last one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// The followed accounts.
    pub follows: Vec<ProfileView>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `get_follows_paged`'s request: `Request` without `cursor`, which the walk advances.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetFollowsPagedRequest {
    /// Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
    pub actor: String,
    /// Rows per page. Range [1, 100]; defaults to 50.
    pub limit: Option<i64>,
    /// Keys the spec does not document, sent as they are.
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl GetFollowsPagedRequest {
    /// The `Request` for one page of the walk.
    fn at(&self, cursor: Option<String>) -> Request {
        Request {
            actor: self.actor.clone(),
            limit: self.limit,
            cursor,
            extra: self.extra.clone(),
        }
    }
}

/// Accounts an account follows, paged by cursor.
#[derive(Clone)]
pub struct GetFollows {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetFollows {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Accounts an account follows, paged by cursor.
    ///
    /// Paged variant of `get_follows`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-graph-get-follows>.
    pub fn get_follows_paged(
        &self,
        request: GetFollowsPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<ProfileView, String> {
        let endpoint = self.clone();
        let next = move |cursor: String| {
            let endpoint = endpoint.clone();
            let request = request.clone();
            let options = options.clone();
            async move {
                let cursor = cursor_or_done(Some(cursor));
                let request = request.at(cursor);
                let response = endpoint.get_follows(request, options).await?;
                let cursor = response.cursor.clone();
                let rows = response.follows;
                Ok((rows, cursor_or_done(cursor)))
            }
        };
        PaginatedResponse::new(String::new(), next)
    }

    /// Accounts an account follows, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-graph-get-follows>.
    pub async fn get_follows(&self, request: Request, options: CallOptions) -> Result<Follows> {
        let raw = self.get_follows_raw(request, options).await?;
        decode(raw)
    }

    /// `get_follows` without validation: the wire body as it came.
    pub async fn get_follows_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(true),
            inject: None,
        };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.graph.getFollows",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
