//! Generated by truewire — do not edit by hand.

pub mod get_followers;
pub mod get_follows;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, PaginatedResponse, Result};

use crate::meta::DefaultMeta;
use crate::types::ProfileView;

/// The social graph: who follows whom (`app.bsky.graph.*`).
///
/// See <https://docs.bsky.app/docs/api/app-bsky-graph-get-followers>.
#[derive(Clone)]
pub struct Graph {
    get_followers: get_followers::GetFollowers,
    get_follows: get_follows::GetFollows,
}

impl Graph {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            get_followers: get_followers::GetFollowers::new(core.clone()),
            get_follows: get_follows::GetFollows::new(core),
        }
    }

    /// Accounts following an account, paged by cursor.
    ///
    /// Paged variant of `get_followers`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-graph-get-followers>.
    pub fn get_followers_paged(
        &self,
        request: get_followers::GetFollowersPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<ProfileView, String> {
        self.get_followers.get_followers_paged(request, options)
    }

    /// Accounts following an account, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-graph-get-followers>.
    pub async fn get_followers(
        &self,
        request: get_followers::Request,
        options: CallOptions,
    ) -> Result<get_followers::Followers> {
        self.get_followers.get_followers(request, options).await
    }

    /// `get_followers` without validation: the wire body as it came.
    pub async fn get_followers_raw(
        &self,
        request: get_followers::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_followers.get_followers_raw(request, options).await
    }

    /// Accounts an account follows, paged by cursor.
    ///
    /// Paged variant of `get_follows`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-graph-get-follows>.
    pub fn get_follows_paged(
        &self,
        request: get_follows::GetFollowsPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<ProfileView, String> {
        self.get_follows.get_follows_paged(request, options)
    }

    /// Accounts an account follows, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-graph-get-follows>.
    pub async fn get_follows(
        &self,
        request: get_follows::Request,
        options: CallOptions,
    ) -> Result<get_follows::Follows> {
        self.get_follows.get_follows(request, options).await
    }

    /// `get_follows` without validation: the wire body as it came.
    pub async fn get_follows_raw(
        &self,
        request: get_follows::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_follows.get_follows_raw(request, options).await
    }
}
