# Generated by truewire — do not edit by hand.
from .get_followers import GetFollowers
from .get_follows import GetFollows


class Graph(GetFollowers, GetFollows):
  """The social graph: who follows whom (`app.bsky.graph.*`).

  References:
    - [Upstream docs](https://docs.bsky.app/docs/api/app-bsky-graph-get-followers)
  """
