// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { RepoCommit } from '../types/index.js'

/** What to write, and where. */
export interface Request {
  /** The repository to write in: a DID or a handle. The session's own `did` in every ordinary use. */
  repo: string
  /** NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything. */
  collection: string
  /** The record itself. Its shape is the collection's own lexicon, which this spec does not model: a `app.bsky.feed.post` wants `$type`, `text` and `createdAt`, and a custom collection wants whatever its author says. Declared as a free-form object rather than a union of every lexicon, because the set is open by design. */
  record: Record<string, unknown>
  /** Record key. Generated by the server when omitted, which is the normal case. */
  rkey?: string
  /** Ask the server to check the record against its lexicon. `validate` is the name every generated method already reserves for its own response-validation override, so the backend renames this one: the Python method takes it as `validate_`. The wire name is unchanged. */
  validate?: boolean
}

export const Request: Codec<Request> = t.object({
  repo: t.string,
  collection: t.string,
  record: t.record(t.unknown),
  rkey: t.optional(t.string),
  validate: t.optional(t.boolean),
})

/** Where the record landed. */
export interface CreatedRecord {
  /** AT URI of the new record (`at://<did>/<collection>/<rkey>`). */
  uri: string
  /** CID of this version of it. */
  cid: string
  commit?: RepoCommit
  /** `valid` when the server checked the record against its lexicon, `unknown` when it has no lexicon to check against -- which is what a custom collection gets. */
  validationStatus?: string
}

export const CreatedRecord: Codec<CreatedRecord> = t.object({
  uri: t.string,
  cid: t.string,
  commit: t.optional(RepoCommit),
  validationStatus: t.optional(t.string),
})

/** Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`. */
export class CreateRecord {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  createRecord(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-repo-create-record
   */
  createRecord(request: Request, options?: CallOptions): Promise<CreatedRecord>
  async createRecord(request: Request, options?: CallOptions): Promise<CreatedRecord> {
    return this.core.request({
      method: 'POST',
      path: '/xrpc/com.atproto.repo.createRecord',
      request,
      requestCodec: Request,
      responseCodec: CreatedRecord,
      meta: { public: false },
      ...options,
    })
  }
}
