// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { RepoCommit } from '../types/index.js'

/** Which record to delete. */
export interface Request {
  /** The repository to write in: a DID or a handle. The session's own `did` in every ordinary use. */
  repo: string
  /** NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything. */
  collection: string
  /** Record key, the last segment of the record's AT URI. */
  rkey: string
}

export const Request: Codec<Request> = t.object({
  repo: t.string,
  collection: t.string,
  rkey: t.string,
})

/** The commit that removed it. */
export interface DeletedRecord {
  commit?: RepoCommit
}

export const DeletedRecord: Codec<DeletedRecord> = t.object({
  commit: t.optional(RepoCommit),
})

/** Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry. */
export class DeleteRecord {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  deleteRecord(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-repo-delete-record
   */
  deleteRecord(request: Request, options?: CallOptions): Promise<DeletedRecord>
  async deleteRecord(request: Request, options?: CallOptions): Promise<DeletedRecord> {
    return this.core.request({
      method: 'POST',
      path: '/xrpc/com.atproto.repo.deleteRecord',
      request,
      requestCodec: Request,
      responseCodec: DeletedRecord,
      meta: { public: false },
      ...options,
    })
  }
}
