// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import * as createRecord from './create_record.js'
import * as deleteRecord from './delete_record.js'

/**
 * Records in the account's own repository (`com.atproto.repo.*`): creating one and deleting it. A post is a record in the `app.bsky.feed.post` collection.
 *
 * @see https://docs.bsky.app/docs/api/com-atproto-repo-create-record
 */
export class Repo {
  private readonly createRecord_: createRecord.CreateRecord
  private readonly deleteRecord_: deleteRecord.DeleteRecord

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.createRecord_ = new createRecord.CreateRecord(core)
    this.deleteRecord_ = new deleteRecord.DeleteRecord(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  createRecord(request: createRecord.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-repo-create-record
   */
  createRecord(request: createRecord.Request, options?: CallOptions): Promise<createRecord.CreatedRecord>
  createRecord(request: createRecord.Request, options?: CallOptions): Promise<createRecord.CreatedRecord> {
    return this.createRecord_.createRecord(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  deleteRecord(request: deleteRecord.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-repo-delete-record
   */
  deleteRecord(request: deleteRecord.Request, options?: CallOptions): Promise<deleteRecord.DeletedRecord>
  deleteRecord(request: deleteRecord.Request, options?: CallOptions): Promise<deleteRecord.DeletedRecord> {
    return this.deleteRecord_.deleteRecord(request, options)
  }
}
