// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import * as resolveHandle from './resolve_handle.js'

/**
 * Handle resolution (`com.atproto.identity.*`).
 *
 * @see https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle
 */
export class Identity {
  private readonly resolveHandle_: resolveHandle.ResolveHandle

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.resolveHandle_ = new resolveHandle.ResolveHandle(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  resolveHandle(request: resolveHandle.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Resolve a handle to its DID.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle
   */
  resolveHandle(request: resolveHandle.Request, options?: CallOptions): Promise<resolveHandle.ResolvedHandle>
  resolveHandle(request: resolveHandle.Request, options?: CallOptions): Promise<resolveHandle.ResolvedHandle> {
    return this.resolveHandle_.resolveHandle(request, options)
  }
}
