// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, PaginatedResponse, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProfileView } from '../types/index.js'

/** Whose followers and which page. */
export interface Request {
  /** Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`. */
  actor: string
  /** Rows per page. Range [1, 100]; defaults to 50. */
  limit?: number
  /** Opaque page token from the previous response; omit for the first page. */
  cursor?: string
}

export const Request: Codec<Request> = t.object({
  actor: t.string,
  limit: t.optional(t.integer),
  cursor: t.optional(t.string),
})

/** One page of followers. */
export interface Followers {
  subject: ProfileView
  /** Token for the next page; absent on the last one. */
  cursor?: string
  /** The followers. */
  followers: ProfileView[]
}

export const Followers: Codec<Followers> = t.object({
  subject: ProfileView,
  cursor: t.optional(t.string),
  followers: t.array(ProfileView),
})

/** `getFollowersPaged`'s request: `Request` without `cursor`, which the walk advances. */
export type GetFollowersPagedRequest = Omit<Request, 'cursor'>

/** Accounts following an account, paged by cursor. */
export class GetFollowers {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollowersPaged(request: GetFollowersPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Accounts following an account, paged by cursor.
   *
   * Paged variant of `getFollowers`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-followers
   */
  getFollowersPaged(request: GetFollowersPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string>
  getFollowersPaged(request: GetFollowersPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string> {
    const next = async (cursor: string): Promise<[ProfileView[], string | null]> => {
      const response = await this.getFollowers({ ...request, cursor: cursor || undefined }, options)
      const rows = response.followers ?? []
      const following = response.cursor ?? null
      return [rows, following || null]
    }
    return new PaginatedResponse('', next)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollowers(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Accounts following an account, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-followers
   */
  getFollowers(request: Request, options?: CallOptions): Promise<Followers>
  async getFollowers(request: Request, options?: CallOptions): Promise<Followers> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.graph.getFollowers',
      request,
      requestCodec: Request,
      responseCodec: Followers,
      meta: { public: true },
      ...options,
    })
  }
}
