// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, PaginatedResponse, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProfileView } from '../types/index.js'

/** Whose follows and which page. */
export interface Request {
  /** Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`. */
  actor: string
  /** Rows per page. Range [1, 100]; defaults to 50. */
  limit?: number
  /** Opaque page token from the previous response; omit for the first page. */
  cursor?: string
}

export const Request: Codec<Request> = t.object({
  actor: t.string,
  limit: t.optional(t.integer),
  cursor: t.optional(t.string),
})

/** One page of follows. */
export interface Follows {
  subject: ProfileView
  /** Token for the next page; absent on the last one. */
  cursor?: string
  /** The followed accounts. */
  follows: ProfileView[]
}

export const Follows: Codec<Follows> = t.object({
  subject: ProfileView,
  cursor: t.optional(t.string),
  follows: t.array(ProfileView),
})

/** `getFollowsPaged`'s request: `Request` without `cursor`, which the walk advances. */
export type GetFollowsPagedRequest = Omit<Request, 'cursor'>

/** Accounts an account follows, paged by cursor. */
export class GetFollows {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollowsPaged(request: GetFollowsPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Accounts an account follows, paged by cursor.
   *
   * Paged variant of `getFollows`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-follows
   */
  getFollowsPaged(request: GetFollowsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string>
  getFollowsPaged(request: GetFollowsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string> {
    const next = async (cursor: string): Promise<[ProfileView[], string | null]> => {
      const response = await this.getFollows({ ...request, cursor: cursor || undefined }, options)
      const rows = response.follows ?? []
      const following = response.cursor ?? null
      return [rows, following || null]
    }
    return new PaginatedResponse('', next)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollows(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Accounts an account follows, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-follows
   */
  getFollows(request: Request, options?: CallOptions): Promise<Follows>
  async getFollows(request: Request, options?: CallOptions): Promise<Follows> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.graph.getFollows',
      request,
      requestCodec: Request,
      responseCodec: Follows,
      meta: { public: true },
      ...options,
    })
  }
}
