// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint, PaginatedResponse } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { ProfileView } from '../types/index.js'
import * as getFollowers from './get_followers.js'
import * as getFollows from './get_follows.js'

/**
 * The social graph: who follows whom (`app.bsky.graph.*`).
 *
 * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-followers
 */
export class Graph {
  private readonly getFollowers_: getFollowers.GetFollowers
  private readonly getFollows_: getFollows.GetFollows

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.getFollowers_ = new getFollowers.GetFollowers(core)
    this.getFollows_ = new getFollows.GetFollows(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollowersPaged(request: getFollowers.GetFollowersPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Accounts following an account, paged by cursor.
   *
   * Paged variant of `getFollowers`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-followers
   */
  getFollowersPaged(request: getFollowers.GetFollowersPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string>
  getFollowersPaged(request: getFollowers.GetFollowersPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string> {
    return this.getFollowers_.getFollowersPaged(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollowers(request: getFollowers.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Accounts following an account, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-followers
   */
  getFollowers(request: getFollowers.Request, options?: CallOptions): Promise<getFollowers.Followers>
  getFollowers(request: getFollowers.Request, options?: CallOptions): Promise<getFollowers.Followers> {
    return this.getFollowers_.getFollowers(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollowsPaged(request: getFollows.GetFollowsPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Accounts an account follows, paged by cursor.
   *
   * Paged variant of `getFollows`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-follows
   */
  getFollowsPaged(request: getFollows.GetFollowsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string>
  getFollowsPaged(request: getFollows.GetFollowsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string> {
    return this.getFollows_.getFollowsPaged(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFollows(request: getFollows.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Accounts an account follows, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-graph-get-follows
   */
  getFollows(request: getFollows.Request, options?: CallOptions): Promise<getFollows.Follows>
  getFollows(request: getFollows.Request, options?: CallOptions): Promise<getFollows.Follows> {
    return this.getFollows_.getFollows(request, options)
  }
}
