// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Which handle. */
export interface Request {
  /** The handle, such as `bsky.app`. */
  handle: string
}

export const Request: Codec<Request> = t.object({
  handle: t.string,
})

/** The DID the handle currently points at. */
export interface ResolvedHandle {
  /** The DID. */
  did: string
}

export const ResolvedHandle: Codec<ResolvedHandle> = t.object({
  did: t.string,
})

/** Resolve a handle to its DID. */
export class ResolveHandle {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  resolveHandle(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Resolve a handle to its DID.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle
   */
  resolveHandle(request: Request, options?: CallOptions): Promise<ResolvedHandle>
  async resolveHandle(request: Request, options?: CallOptions): Promise<ResolvedHandle> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/com.atproto.identity.resolveHandle',
      request,
      requestCodec: Request,
      responseCodec: ResolvedHandle,
      meta: { public: true },
      ...options,
    })
  }
}
