# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import ProfileViewDetailed


class Request(TypedDict):
  """Which account."""

  actor: str
  """Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`."""


class GetProfile(Endpoint):
  """Get one account's full profile with follower, follow and post counts."""

  @overload
  async def get_profile(self, actor: str, *, validate: Literal[False]) -> Any: ...
  @overload
  async def get_profile(
    self,
    actor: str,
    *,
    validate: bool | None = None,
  ) -> ProfileViewDetailed: ...
  async def get_profile(
    self,
    actor: str,
    *,
    validate: bool | None = None,
  ) -> ProfileViewDetailed:
    """Get one account's full profile with follower, follow and post counts.

    Args:
      actor: Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-actor-get-profile)
    """
    return await self.request(
      Request(actor=actor),
      method='GET',
      path='/xrpc/app.bsky.actor.getProfile',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=ProfileViewDetailed,
    )
