//! Generated by truewire — do not edit by hand.

use std::collections::HashMap;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::RepoCommit;

/// What to write, and where.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// The repository to write in: a DID or a handle. The session's own `did` in every ordinary use.
    pub repo: String,
    /// NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything.
    pub collection: String,
    /// The record itself. Its shape is the collection's own lexicon, which this spec does not model: a `app.bsky.feed.post` wants `$type`, `text` and `createdAt`, and a custom collection wants whatever its author says. Declared as a free-form object rather than a union of every lexicon, because the set is open by design.
    pub record: HashMap<String, serde_json::Value>,
    /// Record key. Generated by the server when omitted, which is the normal case.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rkey: Option<String>,
    /// Ask the server to check the record against its lexicon. `validate` is the name every generated method already reserves for its own response-validation override, so the backend renames this one: the Python method takes it as `validate_`. The wire name is unchanged.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Where the record landed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatedRecord {
    /// AT URI of the new record (`at://<did>/<collection>/<rkey>`).
    pub uri: String,
    /// CID of this version of it.
    pub cid: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit: Option<RepoCommit>,
    /// `valid` when the server checked the record against its lexicon, `unknown` when it has no lexicon to check against -- which is what a custom collection gets.
    #[serde(
        rename = "validationStatus",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub validation_status: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`.
#[derive(Clone)]
pub struct CreateRecord {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl CreateRecord {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-repo-create-record>.
    pub async fn create_record(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<CreatedRecord> {
        let raw = self.create_record_raw(request, options).await?;
        decode(raw)
    }

    /// `create_record` without validation: the wire body as it came.
    pub async fn create_record_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(false),
            inject: None,
        };
        let call = HttpCall {
            method: Some("POST"),
            path: "/xrpc/com.atproto.repo.createRecord",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
