//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::RepoCommit;

/// Which record to delete.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// The repository to write in: a DID or a handle. The session's own `did` in every ordinary use.
    pub repo: String,
    /// NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything.
    pub collection: String,
    /// Record key, the last segment of the record's AT URI.
    pub rkey: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The commit that removed it.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DeletedRecord {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit: Option<RepoCommit>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry.
#[derive(Clone)]
pub struct DeleteRecord {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl DeleteRecord {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-repo-delete-record>.
    pub async fn delete_record(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<DeletedRecord> {
        let raw = self.delete_record_raw(request, options).await?;
        decode(raw)
    }

    /// `delete_record` without validation: the wire body as it came.
    pub async fn delete_record_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(false),
            inject: None,
        };
        let call = HttpCall {
            method: Some("POST"),
            path: "/xrpc/com.atproto.repo.deleteRecord",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
