//! Generated by truewire — do not edit by hand.

pub mod create_record;
pub mod delete_record;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// Records in the account's own repository (`com.atproto.repo.*`): creating one and deleting it. A post is a record in the `app.bsky.feed.post` collection.
///
/// See <https://docs.bsky.app/docs/api/com-atproto-repo-create-record>.
#[derive(Clone)]
pub struct Repo {
    create_record: create_record::CreateRecord,
    delete_record: delete_record::DeleteRecord,
}

impl Repo {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            create_record: create_record::CreateRecord::new(core.clone()),
            delete_record: delete_record::DeleteRecord::new(core),
        }
    }

    /// Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-repo-create-record>.
    pub async fn create_record(
        &self,
        request: create_record::Request,
        options: CallOptions,
    ) -> Result<create_record::CreatedRecord> {
        self.create_record.create_record(request, options).await
    }

    /// `create_record` without validation: the wire body as it came.
    pub async fn create_record_raw(
        &self,
        request: create_record::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.create_record.create_record_raw(request, options).await
    }

    /// Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-repo-delete-record>.
    pub async fn delete_record(
        &self,
        request: delete_record::Request,
        options: CallOptions,
    ) -> Result<delete_record::DeletedRecord> {
        self.delete_record.delete_record(request, options).await
    }

    /// `delete_record` without validation: the wire body as it came.
    pub async fn delete_record_raw(
        &self,
        request: delete_record::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.delete_record.delete_record_raw(request, options).await
    }
}
