//! Generated by truewire — do not edit by hand.

pub mod resolve_handle;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// Handle resolution (`com.atproto.identity.*`).
///
/// See <https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle>.
#[derive(Clone)]
pub struct Identity {
    resolve_handle: resolve_handle::ResolveHandle,
}

impl Identity {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            resolve_handle: resolve_handle::ResolveHandle::new(core),
        }
    }

    /// Resolve a handle to its DID.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle>.
    pub async fn resolve_handle(
        &self,
        request: resolve_handle::Request,
        options: CallOptions,
    ) -> Result<resolve_handle::ResolvedHandle> {
        self.resolve_handle.resolve_handle(request, options).await
    }

    /// `resolve_handle` without validation: the wire body as it came.
    pub async fn resolve_handle_raw(
        &self,
        request: resolve_handle::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.resolve_handle
            .resolve_handle_raw(request, options)
            .await
    }
}
