//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// Which handle.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// The handle, such as `bsky.app`.
    pub handle: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The DID the handle currently points at.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolvedHandle {
    /// The DID.
    pub did: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Resolve a handle to its DID.
#[derive(Clone)]
pub struct ResolveHandle {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ResolveHandle {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Resolve a handle to its DID.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle>.
    pub async fn resolve_handle(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ResolvedHandle> {
        let raw = self.resolve_handle_raw(request, options).await?;
        decode(raw)
    }

    /// `resolve_handle` without validation: the wire body as it came.
    pub async fn resolve_handle_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { public: Some(true) };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/com.atproto.identity.resolveHandle",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
