# Generated by truewire — do not edit by hand.
from .create_session import CreateSession
from .refresh_session import RefreshSession


class Server(CreateSession, RefreshSession):
  """Sessions (`com.atproto.server.*`): exchanging an app password for a session, and refreshing it. Everything else in this client is read-only and needs none of it.

  References:
    - [Upstream docs](https://docs.bsky.app/docs/api/com-atproto-server-create-session)
  """
