# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint


class Request(TypedDict):
  """Takes nothing from the caller. The identifier and the app password belong to the client, not to the call: `Bluesky.new(identifier=..., app_password=...)` holds them and the transport injects them at send time. That is why they are not properties here, and why no recorded example of this endpoint can contain a credential -- there is no field for one to sit in."""


class Session(TypedDict):
  """A session: two tokens and who they belong to."""

  accessJwt: str
  """Bearer token for authenticated calls. Short-lived -- minutes, not days -- so a long-running client refreshes rather than reusing it."""
  refreshJwt: str
  """Token that buys a new `accessJwt` from `server.refresh_session`. Longer-lived, and the more dangerous of the two to leak."""
  handle: str
  """Handle the session belongs to, such as `truewire.dev`."""
  did: str
  """DID the session belongs to."""
  active: NotRequired[bool]
  """Whether the account is active. A deactivated or taken-down account still authenticates and answers `false` here."""
  email: NotRequired[str]
  """Account email. Present on `createSession` and absent from `refreshSession`; it is personal data, so recorded examples scrub it."""
  emailConfirmed: NotRequired[bool]
  """Whether that address has been confirmed."""


class CreateSession(Endpoint):
  """Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it."""

  @overload
  async def create_session(self, *, validate: Literal[False]) -> Any: ...
  @overload
  async def create_session(self, *, validate: bool | None = None) -> Session: ...
  async def create_session(self, *, validate: bool | None = None) -> Session:
    """Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/com-atproto-server-create-session)
    """
    return await self.request(
      Request(),
      method='POST',
      path='/xrpc/com.atproto.server.createSession',
      meta={'public': True, 'inject': 'password'},
      validate=validate,
      request_type=Request,
      response_type=Session,
    )
