# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint


class Request(TypedDict):
  """Takes nothing. The refresh token travels as the bearer, in place of the access token -- which is the whole reason this endpoint declares `inject: refresh` rather than being an ordinary authenticated call."""


class Session(TypedDict):
  """A session: two tokens and who they belong to."""

  accessJwt: str
  """Bearer token for authenticated calls. Short-lived -- minutes, not days -- so a long-running client refreshes rather than reusing it."""
  refreshJwt: str
  """Token that buys a new `accessJwt` from `server.refresh_session`. Longer-lived, and the more dangerous of the two to leak."""
  handle: str
  """Handle the session belongs to, such as `truewire.dev`."""
  did: str
  """DID the session belongs to."""
  active: NotRequired[bool]
  """Whether the account is active. A deactivated or taken-down account still authenticates and answers `false` here."""
  email: NotRequired[str]
  """Account email. Present on `createSession` and absent from `refreshSession`; it is personal data, so recorded examples scrub it."""
  emailConfirmed: NotRequired[bool]
  """Whether that address has been confirmed."""


class RefreshSession(Endpoint):
  """Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up."""

  @overload
  async def refresh_session(self, *, validate: Literal[False]) -> Any: ...
  @overload
  async def refresh_session(self, *, validate: bool | None = None) -> Session: ...
  async def refresh_session(self, *, validate: bool | None = None) -> Session:
    """Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/com-atproto-server-refresh-session)
    """
    return await self.request(
      Request(),
      method='POST',
      path='/xrpc/com.atproto.server.refreshSession',
      meta={'public': True, 'inject': 'refresh'},
      validate=validate,
      request_type=Request,
      response_type=Session,
    )
