// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProfileViewDetailed } from '../types/index.js'

/** Which account. */
export interface Request {
  /** Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`. */
  actor: string
}

export const Request: Codec<Request> = t.object({
  actor: t.string,
})

/** Get one account's full profile with follower, follow and post counts. */
export class GetProfile {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getProfile(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get one account's full profile with follower, follow and post counts.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-get-profile
   */
  getProfile(request: Request, options?: CallOptions): Promise<ProfileViewDetailed>
  async getProfile(request: Request, options?: CallOptions): Promise<ProfileViewDetailed> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.actor.getProfile',
      request,
      requestCodec: Request,
      responseCodec: ProfileViewDetailed,
      meta: { public: true },
      ...options,
    })
  }
}
