// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint, PaginatedResponse } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { ProfileView, ProfileViewDetailed } from '../types/index.js'
import * as getProfile from './get_profile.js'
import * as getProfiles from './get_profiles.js'
import * as searchActors from './search_actors.js'

/**
 * Profiles: one, several, or by search (`app.bsky.actor.*`).
 *
 * @see https://docs.bsky.app/docs/api/app-bsky-actor-get-profile
 */
export class Actor {
  private readonly getProfile_: getProfile.GetProfile
  private readonly getProfiles_: getProfiles.GetProfiles
  private readonly searchActors_: searchActors.SearchActors

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.getProfile_ = new getProfile.GetProfile(core)
    this.getProfiles_ = new getProfiles.GetProfiles(core)
    this.searchActors_ = new searchActors.SearchActors(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getProfile(request: getProfile.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get one account's full profile with follower, follow and post counts.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-get-profile
   */
  getProfile(request: getProfile.Request, options?: CallOptions): Promise<ProfileViewDetailed>
  getProfile(request: getProfile.Request, options?: CallOptions): Promise<ProfileViewDetailed> {
    return this.getProfile_.getProfile(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getProfiles(request: getProfiles.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get up to 25 full profiles in one call.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-get-profiles
   */
  getProfiles(request: getProfiles.Request, options?: CallOptions): Promise<getProfiles.Profiles>
  getProfiles(request: getProfiles.Request, options?: CallOptions): Promise<getProfiles.Profiles> {
    return this.getProfiles_.getProfiles(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchActorsPaged(request: searchActors.SearchActorsPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Search accounts by name or handle, paged by cursor.
   *
   * Paged variant of `searchActors`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-search-actors
   */
  searchActorsPaged(request: searchActors.SearchActorsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string>
  searchActorsPaged(request: searchActors.SearchActorsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string> {
    return this.searchActors_.searchActorsPaged(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchActors(request: searchActors.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Search accounts by name or handle, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-search-actors
   */
  searchActors(request: searchActors.Request, options?: CallOptions): Promise<searchActors.ActorSearchResults>
  searchActors(request: searchActors.Request, options?: CallOptions): Promise<searchActors.ActorSearchResults> {
    return this.searchActors_.searchActors(request, options)
  }
}
