// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, PaginatedResponse, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProfileView } from '../types/index.js'

/** The query and the page. */
export interface Request {
  /** Search string, matched against handles, display names and bios. */
  q: string
  /** Rows per page. Range [1, 100]; defaults to 25. */
  limit?: number
  /** Opaque page token from the previous response; omit for the first page. */
  cursor?: string
}

export const Request: Codec<Request> = t.object({
  q: t.string,
  limit: t.optional(t.integer),
  cursor: t.optional(t.string),
})

/** One page of matching profiles. */
export interface ActorSearchResults {
  /** Token for the next page; absent on the last one. */
  cursor?: string
  /** Matching profiles, best first. */
  actors: ProfileView[]
}

export const ActorSearchResults: Codec<ActorSearchResults> = t.object({
  cursor: t.optional(t.string),
  actors: t.array(ProfileView),
})

/** `searchActorsPaged`'s request: `Request` without `cursor`, which the walk advances. */
export type SearchActorsPagedRequest = Omit<Request, 'cursor'>

/** Search accounts by name or handle, paged by cursor. */
export class SearchActors {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchActorsPaged(request: SearchActorsPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Search accounts by name or handle, paged by cursor.
   *
   * Paged variant of `searchActors`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-search-actors
   */
  searchActorsPaged(request: SearchActorsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string>
  searchActorsPaged(request: SearchActorsPagedRequest, options?: CallOptions): PaginatedResponse<ProfileView, string> {
    const next = async (cursor: string): Promise<[ProfileView[], string | null]> => {
      const response = await this.searchActors({ ...request, cursor: cursor || undefined }, options)
      const rows = response.actors ?? []
      const following = response.cursor ?? null
      return [rows, following || null]
    }
    return new PaginatedResponse('', next)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchActors(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Search accounts by name or handle, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-search-actors
   */
  searchActors(request: Request, options?: CallOptions): Promise<ActorSearchResults>
  async searchActors(request: Request, options?: CallOptions): Promise<ActorSearchResults> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.actor.searchActors',
      request,
      requestCodec: Request,
      responseCodec: ActorSearchResults,
      meta: { public: true },
      ...options,
    })
  }
}
