// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Takes nothing from the caller. The identifier and the app password belong to the client, not to the call: `Bluesky.new(identifier=..., app_password=...)` holds them and the transport injects them at send time. That is why they are not properties here, and why no recorded example of this endpoint can contain a credential -- there is no field for one to sit in. */
export interface Request {}

export const Request: Codec<Request> = t.object({})

/** A session: two tokens and who they belong to. */
export interface Session {
  /** Bearer token for authenticated calls. Short-lived -- minutes, not days -- so a long-running client refreshes rather than reusing it. */
  accessJwt: string
  /** Token that buys a new `accessJwt` from `server.refresh_session`. Longer-lived, and the more dangerous of the two to leak. */
  refreshJwt: string
  /** Handle the session belongs to, such as `truewire.dev`. */
  handle: string
  /** DID the session belongs to. */
  did: string
  /** Whether the account is active. A deactivated or taken-down account still authenticates and answers `false` here. */
  active?: boolean
  /** Account email. Present on `createSession` and absent from `refreshSession`; it is personal data, so recorded examples scrub it. */
  email?: string
  /** Whether that address has been confirmed. */
  emailConfirmed?: boolean
}

export const Session: Codec<Session> = t.object({
  accessJwt: t.string,
  refreshJwt: t.string,
  handle: t.string,
  did: t.string,
  active: t.optional(t.boolean),
  email: t.optional(t.string),
  emailConfirmed: t.optional(t.boolean),
})

/** Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it. */
export class CreateSession {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  createSession(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-server-create-session
   */
  createSession(request?: Request, options?: CallOptions): Promise<Session>
  async createSession(request?: Request, options?: CallOptions): Promise<Session> {
    return this.core.request({
      method: 'POST',
      path: '/xrpc/com.atproto.server.createSession',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: Session,
      meta: { public: true, inject: 'password' },
      ...options,
    })
  }
}
