// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import * as createSession from './create_session.js'
import * as refreshSession from './refresh_session.js'

/**
 * Sessions (`com.atproto.server.*`): exchanging an app password for a session, and refreshing it. Everything else in this client is read-only and needs none of it.
 *
 * @see https://docs.bsky.app/docs/api/com-atproto-server-create-session
 */
export class Server {
  private readonly createSession_: createSession.CreateSession
  private readonly refreshSession_: refreshSession.RefreshSession

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.createSession_ = new createSession.CreateSession(core)
    this.refreshSession_ = new refreshSession.RefreshSession(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  createSession(request: createSession.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-server-create-session
   */
  createSession(request?: createSession.Request, options?: CallOptions): Promise<createSession.Session>
  createSession(request?: createSession.Request, options?: CallOptions): Promise<createSession.Session> {
    return this.createSession_.createSession(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  refreshSession(request: refreshSession.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-server-refresh-session
   */
  refreshSession(request?: refreshSession.Request, options?: CallOptions): Promise<refreshSession.Session>
  refreshSession(request?: refreshSession.Request, options?: CallOptions): Promise<refreshSession.Session> {
    return this.refreshSession_.refreshSession(request, options)
  }
}
