// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Takes nothing. The refresh token travels as the bearer, in place of the access token -- which is the whole reason this endpoint declares `inject: refresh` rather than being an ordinary authenticated call. */
export interface Request {}

export const Request: Codec<Request> = t.object({})

/** A session: two tokens and who they belong to. */
export interface Session {
  /** Bearer token for authenticated calls. Short-lived -- minutes, not days -- so a long-running client refreshes rather than reusing it. */
  accessJwt: string
  /** Token that buys a new `accessJwt` from `server.refresh_session`. Longer-lived, and the more dangerous of the two to leak. */
  refreshJwt: string
  /** Handle the session belongs to, such as `truewire.dev`. */
  handle: string
  /** DID the session belongs to. */
  did: string
  /** Whether the account is active. A deactivated or taken-down account still authenticates and answers `false` here. */
  active?: boolean
  /** Account email. Present on `createSession` and absent from `refreshSession`; it is personal data, so recorded examples scrub it. */
  email?: string
  /** Whether that address has been confirmed. */
  emailConfirmed?: boolean
}

export const Session: Codec<Session> = t.object({
  accessJwt: t.string,
  refreshJwt: t.string,
  handle: t.string,
  did: t.string,
  active: t.optional(t.boolean),
  email: t.optional(t.string),
  emailConfirmed: t.optional(t.boolean),
})

/** Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up. */
export class RefreshSession {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  refreshSession(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up.
   *
   * @see https://docs.bsky.app/docs/api/com-atproto-server-refresh-session
   */
  refreshSession(request?: Request, options?: CallOptions): Promise<Session>
  async refreshSession(request?: Request, options?: CallOptions): Promise<Session> {
    return this.core.request({
      method: 'POST',
      path: '/xrpc/com.atproto.server.refreshSession',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: Session,
      meta: { public: true, inject: 'refresh' },
      ...options,
    })
  }
}
