# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import ProfileView


class Request(TypedDict):
  """Whose follows and which page."""

  actor: str
  """Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`."""
  limit: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 50."""
  cursor: NotRequired[str]
  """Opaque page token from the previous response; omit for the first page."""


class Follows(TypedDict):
  """One page of follows."""

  subject: ProfileView
  cursor: NotRequired[str]
  """Token for the next page; absent on the last one."""
  follows: list[ProfileView]
  """The followed accounts."""


class GetFollows(Endpoint):
  """Accounts an account follows, paged by cursor."""

  @overload
  def get_follows_paged(
    self,
    *,
    actor: str,
    limit: int | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def get_follows_paged(
    self,
    *,
    actor: str,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[ProfileView, str]: ...
  def get_follows_paged(
    self,
    *,
    actor: str,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[ProfileView, str]:
    """Accounts an account follows, paged by cursor.

    Paged variant of `get_follows`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      actor: Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
      limit: Rows per page. Range [1, 100]; defaults to 50.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-graph-get-follows)
    """

    async def next(cursor: str) -> tuple[list[ProfileView], str | None]:
      response = await self.get_follows(
        actor=actor, limit=limit, cursor=(cursor or None), validate=validate
      )
      rows = response.get('follows')
      state = response.get('cursor')
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def get_follows(
    self,
    *,
    actor: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_follows(
    self,
    *,
    actor: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> Follows: ...
  async def get_follows(
    self,
    *,
    actor: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> Follows:
    """Accounts an account follows, paged by cursor.

    Args:
      actor: Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
      limit: Rows per page. Range [1, 100]; defaults to 50.
      cursor: Opaque page token from the previous response; omit for the first page.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-graph-get-follows)
    """
    request: Request = Request(actor=actor)
    if limit is not None:
      request['limit'] = limit
    if cursor is not None:
      request['cursor'] = cursor
    return await self.request(
      request,
      method='GET',
      path='/xrpc/app.bsky.graph.getFollows',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=Follows,
    )
