# Generated by truewire — do not edit by hand.
from .get_profile import GetProfile
from .get_profiles import GetProfiles
from .search_actors import SearchActors


class Actor(GetProfile, GetProfiles, SearchActors):
  """Profiles: one, several, or by search (`app.bsky.actor.*`).

  References:
    - [Upstream docs](https://docs.bsky.app/docs/api/app-bsky-actor-get-profile)
  """
