# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import ProfileViewDetailed


class Request(TypedDict):
  """Which accounts."""

  actors: list[str]
  """Handles or DIDs, at most 25. Sent as repeated `actors` query parameters."""


class Profiles(TypedDict):
  """The profiles, in the order asked for; an unresolvable actor is left out."""

  profiles: list[ProfileViewDetailed]
  """The profiles."""


class GetProfiles(Endpoint):
  """Get up to 25 full profiles in one call."""

  @overload
  async def get_profiles(
    self,
    actors: list[str],
    *,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_profiles(
    self,
    actors: list[str],
    *,
    validate: bool | None = None,
  ) -> Profiles: ...
  async def get_profiles(
    self,
    actors: list[str],
    *,
    validate: bool | None = None,
  ) -> Profiles:
    """Get up to 25 full profiles in one call.

    Args:
      actors: Handles or DIDs, at most 25. Sent as repeated `actors` query parameters.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-actor-get-profiles)
    """
    return await self.request(
      Request(actors=actors),
      method='GET',
      path='/xrpc/app.bsky.actor.getProfiles',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=Profiles,
    )
