# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import ProfileView


class Request(TypedDict):
  """The query and the page."""

  q: str
  """Search string, matched against handles, display names and bios."""
  limit: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 25."""
  cursor: NotRequired[str]
  """Opaque page token from the previous response; omit for the first page."""


class ActorSearchResults(TypedDict):
  """One page of matching profiles."""

  cursor: NotRequired[str]
  """Token for the next page; absent on the last one."""
  actors: list[ProfileView]
  """Matching profiles, best first."""


class SearchActors(Endpoint):
  """Search accounts by name or handle, paged by cursor."""

  @overload
  def search_actors_paged(
    self,
    *,
    q: str,
    limit: int | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def search_actors_paged(
    self,
    *,
    q: str,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[ProfileView, str]: ...
  def search_actors_paged(
    self,
    *,
    q: str,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[ProfileView, str]:
    """Search accounts by name or handle, paged by cursor.

    Paged variant of `search_actors`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      q: Search string, matched against handles, display names and bios.
      limit: Rows per page. Range [1, 100]; defaults to 25.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-actor-search-actors)
    """

    async def next(cursor: str) -> tuple[list[ProfileView], str | None]:
      response = await self.search_actors(
        q=q, limit=limit, cursor=(cursor or None), validate=validate
      )
      rows = response.get('actors')
      state = response.get('cursor')
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def search_actors(
    self,
    *,
    q: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def search_actors(
    self,
    *,
    q: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> ActorSearchResults: ...
  async def search_actors(
    self,
    *,
    q: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> ActorSearchResults:
    """Search accounts by name or handle, paged by cursor.

    Args:
      q: Search string, matched against handles, display names and bios.
      limit: Rows per page. Range [1, 100]; defaults to 25.
      cursor: Opaque page token from the previous response; omit for the first page.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-actor-search-actors)
    """
    request: Request = Request(q=q)
    if limit is not None:
      request['limit'] = limit
    if cursor is not None:
      request['cursor'] = cursor
    return await self.request(
      request,
      method='GET',
      path='/xrpc/app.bsky.actor.searchActors',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=ActorSearchResults,
    )
