// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProfileViewDetailed } from '../types/index.js'

/** Which accounts. */
export interface Request {
  /** Handles or DIDs, at most 25. Sent as repeated `actors` query parameters. */
  actors: string[]
}

export const Request: Codec<Request> = t.object({
  actors: t.array(t.string),
})

/** The profiles, in the order asked for; an unresolvable actor is left out. */
export interface Profiles {
  /** The profiles. */
  profiles: ProfileViewDetailed[]
}

export const Profiles: Codec<Profiles> = t.object({
  profiles: t.array(ProfileViewDetailed),
})

/** Get up to 25 full profiles in one call. */
export class GetProfiles {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getProfiles(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get up to 25 full profiles in one call.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-actor-get-profiles
   */
  getProfiles(request: Request, options?: CallOptions): Promise<Profiles>
  async getProfiles(request: Request, options?: CallOptions): Promise<Profiles> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.actor.getProfiles',
      request,
      requestCodec: Request,
      responseCodec: Profiles,
      meta: { public: true },
      ...options,
    })
  }
}
