//! Generated by truewire — do not edit by hand.

use std::collections::HashMap;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, Result, Stream, StreamEndpoint, SubscribeCall,
    TimestampIso, TimestampMicros,
};

/// An account status change; present when `kind` is `account`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccountStatus {
    /// Whether the account is active on its host.
    pub active: bool,
    /// The account's DID.
    pub did: String,
    /// Sequence number on the upstream firehose.
    pub seq: i64,
    /// When the change happened.
    pub time: TimestampIso,
    /// Why the account is inactive, when it is: `takendown`, `suspended`, `deleted` or `deactivated`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CommitOperation {
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "delete")]
    Delete,
}

/// One record operation in the repository; present when `kind` is `commit`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Commit {
    /// Repository revision after this commit.
    pub rev: String,
    /// What happened to the record.
    pub operation: CommitOperation,
    /// Collection NSID of the record, such as `app.bsky.feed.post`.
    pub collection: String,
    /// Record key within the collection.
    pub rkey: String,
    /// The record, for `create` and `update`; absent on `delete`. Any collection's record, so kept as a map: `$type` names the lexicon.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub record: Option<HashMap<String, serde_json::Value>>,
    /// CID of the record, for `create` and `update`; absent on `delete`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// An identity change; present when `kind` is `identity`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Identity {
    /// The DID whose identity changed.
    pub did: String,
    /// The current handle, when it resolved.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    /// Sequence number on the upstream firehose.
    pub seq: i64,
    /// When the change happened.
    pub time: TimestampIso,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The filter and the starting point, sent as the connection URL's query string.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Parameters {
    /// Collection NSIDs to include, such as `app.bsky.feed.post`; a trailing `.*` matches a prefix (`app.bsky.graph.*`). At most 100. Omit for every collection. Sent as repeated `wantedCollections` query parameters.
    #[serde(
        rename = "wantedCollections",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub wanted_collections: Option<Vec<String>>,
    /// DIDs to include, at most 10000. Omit for every account. Sent as repeated `wantedDids` query parameters.
    #[serde(
        rename = "wantedDids",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub wanted_dids: Option<Vec<String>>,
    /// Replay from this instant, as Unix microseconds on the wire; omit to start from now. Jetstream keeps a bounded backlog, and a cursor before it starts from the oldest event kept.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<TimestampMicros>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum JetstreamEventKind {
    #[serde(rename = "commit")]
    Commit,
    #[serde(rename = "identity")]
    Identity,
    #[serde(rename = "account")]
    Account,
}

/// One event. `kind` says which of `commit`, `identity` and `account` is present.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JetstreamEvent {
    /// DID of the repository the event is about.
    pub did: String,
    /// When the event was emitted, as Unix microseconds on the wire. Also the cursor to resume from.
    pub time_us: TimestampMicros,
    /// Event kind: a repository commit, an identity (handle or DID document) change, or an account status change.
    pub kind: JetstreamEventKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit: Option<Commit>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identity: Option<Identity>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account: Option<AccountStatus>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open.
#[derive(Clone)]
pub struct Events {
    core: Arc<dyn StreamEndpoint>,
}

impl Events {
    pub fn new(core: Arc<dyn StreamEndpoint>) -> Self {
        Self { core }
    }

    /// Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open.
    ///
    /// See <https://github.com/bluesky-social/jetstream#consuming-jetstream>.
    pub async fn events(
        &self,
        parameters: Parameters,
        options: CallOptions,
    ) -> Result<Stream<JetstreamEvent>> {
        let stream = self.events_raw(parameters, options).await?;
        Ok(stream.map(decode))
    }

    /// `events` without validation: the frames as they came.
    pub async fn events_raw(
        &self,
        parameters: Parameters,
        options: CallOptions,
    ) -> Result<Stream<serde_json::Value>> {
        let call = SubscribeCall {
            channel: "subscribe",
            parameters: Some(dump(&parameters)?),
            meta: &(),
            options,
        };
        self.core.subscribe(call).await
    }
}
