//! Generated by truewire — do not edit by hand.

pub mod events;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, Result, Stream, StreamEndpoint};

/// Jetstream: Bluesky's JSON firehose of repository commits, identity changes and account status changes, over one WebSocket per subscription.
///
/// See <https://github.com/bluesky-social/jetstream>.
#[derive(Clone)]
pub struct Jetstream {
    events: events::Events,
}

impl Jetstream {
    pub fn new(core: Arc<dyn StreamEndpoint>) -> Self {
        Self {
            events: events::Events::new(core),
        }
    }

    /// Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open.
    ///
    /// See <https://github.com/bluesky-social/jetstream#consuming-jetstream>.
    pub async fn events(
        &self,
        parameters: events::Parameters,
        options: CallOptions,
    ) -> Result<Stream<events::JetstreamEvent>> {
        self.events.events(parameters, options).await
    }

    /// `events` without validation: the frames as they came.
    pub async fn events_raw(
        &self,
        parameters: events::Parameters,
        options: CallOptions,
    ) -> Result<Stream<serde_json::Value>> {
        self.events.events_raw(parameters, options).await
    }
}
