# Generated by truewire — do not edit by hand.
from .create_record import CreateRecord
from .delete_record import DeleteRecord


class Repo(CreateRecord, DeleteRecord):
  """Records in the account's own repository (`com.atproto.repo.*`): creating one and deleting it. A post is a record in the `app.bsky.feed.post` collection.

  References:
    - [Upstream docs](https://docs.bsky.app/docs/api/com-atproto-repo-create-record)
  """
