# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import RepoCommit


class Request(TypedDict):
  """What to write, and where."""

  repo: str
  """The repository to write in: a DID or a handle. The session's own `did` in every ordinary use."""
  collection: str
  """NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything."""
  record: dict[str, Any]
  """The record itself. Its shape is the collection's own lexicon, which this spec does not model: a `app.bsky.feed.post` wants `$type`, `text` and `createdAt`, and a custom collection wants whatever its author says. Declared as a free-form object rather than a union of every lexicon, because the set is open by design."""
  rkey: NotRequired[str]
  """Record key. Generated by the server when omitted, which is the normal case."""
  validate: NotRequired[bool]
  """Ask the server to check the record against its lexicon. `validate` is the name every generated method already reserves for its own response-validation override, so the backend renames this one: the Python method takes it as `validate_`. The wire name is unchanged."""


class CreatedRecord(TypedDict):
  """Where the record landed."""

  uri: str
  """AT URI of the new record (`at://<did>/<collection>/<rkey>`)."""
  cid: str
  """CID of this version of it."""
  commit: NotRequired[RepoCommit]
  validationStatus: NotRequired[str]
  """`valid` when the server checked the record against its lexicon, `unknown` when it has no lexicon to check against -- which is what a custom collection gets."""


class CreateRecord(Endpoint):
  """Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`."""

  @overload
  async def create_record(
    self,
    *,
    repo: str,
    collection: str,
    record: dict[str, Any],
    rkey: str | None = None,
    validate_: bool | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def create_record(
    self,
    *,
    repo: str,
    collection: str,
    record: dict[str, Any],
    rkey: str | None = None,
    validate_: bool | None = None,
    validate: bool | None = None,
  ) -> CreatedRecord: ...
  async def create_record(
    self,
    *,
    repo: str,
    collection: str,
    record: dict[str, Any],
    rkey: str | None = None,
    validate_: bool | None = None,
    validate: bool | None = None,
  ) -> CreatedRecord:
    """Write one record into a collection of the account's repository. A post is exactly this, with `collection: "app.bsky.feed.post"` and a record carrying `text` and `createdAt`.

    Args:
      repo: The repository to write in: a DID or a handle. The session's own `did` in every ordinary use.
      collection: NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything.
      record: The record itself. Its shape is the collection's own lexicon, which this spec does not model: a `app.bsky.feed.post` wants `$type`, `text` and `createdAt`, and a custom collection wants whatever its author says. Declared as a free-form object rather than a union of every lexicon, because the set is open by design.
      rkey: Record key. Generated by the server when omitted, which is the normal case.
      validate_: Ask the server to check the record against its lexicon. `validate` is the name every generated method already reserves for its own response-validation override, so the backend renames this one: the Python method takes it as `validate_`. The wire name is unchanged.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/com-atproto-repo-create-record)
    """
    request: Request = Request(repo=repo, collection=collection, record=record)
    if rkey is not None:
      request['rkey'] = rkey
    if validate_ is not None:
      request['validate'] = validate_
    return await self.request(
      request,
      method='POST',
      path='/xrpc/com.atproto.repo.createRecord',
      meta={'public': False},
      validate=validate,
      request_type=Request,
      response_type=CreatedRecord,
    )
