# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import RepoCommit


class Request(TypedDict):
  """Which record to delete."""

  repo: str
  """The repository to write in: a DID or a handle. The session's own `did` in every ordinary use."""
  collection: str
  """NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything."""
  rkey: str
  """Record key, the last segment of the record's AT URI."""


class DeletedRecord(TypedDict):
  """The commit that removed it."""

  commit: NotRequired[RepoCommit]


class DeleteRecord(Endpoint):
  """Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry."""

  @overload
  async def delete_record(
    self,
    *,
    repo: str,
    collection: str,
    rkey: str,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def delete_record(
    self,
    *,
    repo: str,
    collection: str,
    rkey: str,
    validate: bool | None = None,
  ) -> DeletedRecord: ...
  async def delete_record(
    self,
    *,
    repo: str,
    collection: str,
    rkey: str,
    validate: bool | None = None,
  ) -> DeletedRecord:
    """Delete one record from a collection. Deleting a record that is already gone succeeds rather than failing, so this is safe to retry.

    Args:
      repo: The repository to write in: a DID or a handle. The session's own `did` in every ordinary use.
      collection: NSID of the collection, such as `app.bsky.feed.post` for a post. Any NSID is accepted -- a PDS stores records in collections nothing renders, which is how this client's examples are recorded without publishing anything.
      rkey: Record key, the last segment of the record's AT URI.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/com-atproto-repo-delete-record)
    """
    return await self.request(
      Request(repo=repo, collection=collection, rkey=rkey),
      method='POST',
      path='/xrpc/com.atproto.repo.deleteRecord',
      meta={'public': False},
      validate=validate,
      request_type=Request,
      response_type=DeletedRecord,
    )
