//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// Takes nothing from the caller. The identifier and the app password belong to the client, not to the call: `Bluesky.new(identifier=..., app_password=...)` holds them and the transport injects them at send time. That is why they are not properties here, and why no recorded example of this endpoint can contain a credential -- there is no field for one to sit in.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A session: two tokens and who they belong to.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Session {
    /// Bearer token for authenticated calls. Short-lived -- minutes, not days -- so a long-running client refreshes rather than reusing it.
    #[serde(rename = "accessJwt")]
    pub access_jwt: String,
    /// Token that buys a new `accessJwt` from `server.refresh_session`. Longer-lived, and the more dangerous of the two to leak.
    #[serde(rename = "refreshJwt")]
    pub refresh_jwt: String,
    /// Handle the session belongs to, such as `truewire.dev`.
    pub handle: String,
    /// DID the session belongs to.
    pub did: String,
    /// Whether the account is active. A deactivated or taken-down account still authenticates and answers `false` here.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Account email. Present on `createSession` and absent from `refreshSession`; it is personal data, so recorded examples scrub it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Whether that address has been confirmed.
    #[serde(
        rename = "emailConfirmed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub email_confirmed: Option<bool>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it.
#[derive(Clone)]
pub struct CreateSession {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl CreateSession {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-server-create-session>.
    pub async fn create_session(&self, request: Request, options: CallOptions) -> Result<Session> {
        let raw = self.create_session_raw(request, options).await?;
        decode(raw)
    }

    /// `create_session` without validation: the wire body as it came.
    pub async fn create_session_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(true),
            inject: Some("password".to_string()),
        };
        let call = HttpCall {
            method: Some("POST"),
            path: "/xrpc/com.atproto.server.createSession",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
