//! Generated by truewire — do not edit by hand.

pub mod create_session;
pub mod refresh_session;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// Sessions (`com.atproto.server.*`): exchanging an app password for a session, and refreshing it. Everything else in this client is read-only and needs none of it.
///
/// See <https://docs.bsky.app/docs/api/com-atproto-server-create-session>.
#[derive(Clone)]
pub struct Server {
    create_session: create_session::CreateSession,
    refresh_session: refresh_session::RefreshSession,
}

impl Server {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            create_session: create_session::CreateSession::new(core.clone()),
            refresh_session: refresh_session::RefreshSession::new(core),
        }
    }

    /// Exchange an app password for a session. The core calls this by itself before the first authenticated request, so a caller normally never touches it.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-server-create-session>.
    pub async fn create_session(
        &self,
        request: create_session::Request,
        options: CallOptions,
    ) -> Result<create_session::Session> {
        self.create_session.create_session(request, options).await
    }

    /// `create_session` without validation: the wire body as it came.
    pub async fn create_session_raw(
        &self,
        request: create_session::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.create_session
            .create_session_raw(request, options)
            .await
    }

    /// Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-server-refresh-session>.
    pub async fn refresh_session(
        &self,
        request: refresh_session::Request,
        options: CallOptions,
    ) -> Result<refresh_session::Session> {
        self.refresh_session.refresh_session(request, options).await
    }

    /// `refresh_session` without validation: the wire body as it came.
    pub async fn refresh_session_raw(
        &self,
        request: refresh_session::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.refresh_session
            .refresh_session_raw(request, options)
            .await
    }
}
