//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// Takes nothing. The refresh token travels as the bearer, in place of the access token -- which is the whole reason this endpoint declares `inject: refresh` rather than being an ordinary authenticated call.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A session: two tokens and who they belong to.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Session {
    /// Bearer token for authenticated calls. Short-lived -- minutes, not days -- so a long-running client refreshes rather than reusing it.
    #[serde(rename = "accessJwt")]
    pub access_jwt: String,
    /// Token that buys a new `accessJwt` from `server.refresh_session`. Longer-lived, and the more dangerous of the two to leak.
    #[serde(rename = "refreshJwt")]
    pub refresh_jwt: String,
    /// Handle the session belongs to, such as `truewire.dev`.
    pub handle: String,
    /// DID the session belongs to.
    pub did: String,
    /// Whether the account is active. A deactivated or taken-down account still authenticates and answers `false` here.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Account email. Present on `createSession` and absent from `refreshSession`; it is personal data, so recorded examples scrub it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Whether that address has been confirmed.
    #[serde(
        rename = "emailConfirmed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub email_confirmed: Option<bool>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up.
#[derive(Clone)]
pub struct RefreshSession {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl RefreshSession {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Trade a refresh token for a fresh session. The core does this on its own when an access token expires mid-call, retries the call once, and only then gives up.
    ///
    /// See <https://docs.bsky.app/docs/api/com-atproto-server-refresh-session>.
    pub async fn refresh_session(&self, request: Request, options: CallOptions) -> Result<Session> {
        let raw = self.refresh_session_raw(request, options).await?;
        decode(raw)
    }

    /// `refresh_session` without validation: the wire body as it came.
    pub async fn refresh_session_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(true),
            inject: Some("refresh".to_string()),
        };
        let call = HttpCall {
            method: Some("POST"),
            path: "/xrpc/com.atproto.server.refreshSession",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
