# Generated by truewire — do not edit by hand.
from .get_author_feed import GetAuthorFeed
from .get_feed import GetFeed
from .get_post_thread import GetPostThread
from .get_posts import GetPosts
from .search_posts import SearchPosts


class Feed(GetAuthorFeed, GetFeed, GetPostThread, GetPosts, SearchPosts):
  """Posts, threads and feeds (`app.bsky.feed.*`).

  References:
    - [Upstream docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed)
  """
