# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import FeedViewPost


class Request(TypedDict):
  """Which feed and which page."""

  feed: str
  """AT URI of the feed generator record (`app.bsky.feed.generator`)."""
  limit: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 50."""
  cursor: NotRequired[str]
  """Opaque page token from the previous response; omit for the first page."""


class Feed(TypedDict):
  """One page of the feed."""

  cursor: NotRequired[str]
  """Token for the next page; absent on the last one."""
  feed: list[FeedViewPost]
  """Feed entries, in the generator's order."""


class GetFeed(Endpoint):
  """A custom feed, served through its feed generator, paged by cursor."""

  @overload
  def get_feed_paged(
    self,
    *,
    feed: str,
    limit: int | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def get_feed_paged(
    self,
    *,
    feed: str,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[FeedViewPost, str]: ...
  def get_feed_paged(
    self,
    *,
    feed: str,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[FeedViewPost, str]:
    """A custom feed, served through its feed generator, paged by cursor.

    Paged variant of `get_feed`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      feed: AT URI of the feed generator record (`app.bsky.feed.generator`).
      limit: Rows per page. Range [1, 100]; defaults to 50.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-feed)
    """

    async def next(cursor: str) -> tuple[list[FeedViewPost], str | None]:
      response = await self.get_feed(
        feed=feed, limit=limit, cursor=(cursor or None), validate=validate
      )
      rows = response.get('feed')
      state = response.get('cursor')
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def get_feed(
    self,
    *,
    feed: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_feed(
    self,
    *,
    feed: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> Feed: ...
  async def get_feed(
    self,
    *,
    feed: str,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> Feed:
    """A custom feed, served through its feed generator, paged by cursor.

    Args:
      feed: AT URI of the feed generator record (`app.bsky.feed.generator`).
      limit: Rows per page. Range [1, 100]; defaults to 50.
      cursor: Opaque page token from the previous response; omit for the first page.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-feed)
    """
    request: Request = Request(feed=feed)
    if limit is not None:
      request['limit'] = limit
    if cursor is not None:
      request['cursor'] = cursor
    return await self.request(
      request,
      method='GET',
      path='/xrpc/app.bsky.feed.getFeed',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=Feed,
    )
