# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import PostView


class Request(TypedDict):
  """Which posts."""

  uris: list[str]
  """AT URIs of the posts, at most 25. Sent as repeated `uris` query parameters."""


class Posts(TypedDict):
  """The posts that exist, in the order asked for."""

  posts: list[PostView]
  """The posts."""


class GetPosts(Endpoint):
  """Get up to 25 posts by AT URI in one call."""

  @overload
  async def get_posts(self, uris: list[str], *, validate: Literal[False]) -> Any: ...
  @overload
  async def get_posts(
    self,
    uris: list[str],
    *,
    validate: bool | None = None,
  ) -> Posts: ...
  async def get_posts(self, uris: list[str], *, validate: bool | None = None) -> Posts:
    """Get up to 25 posts by AT URI in one call.

    Args:
      uris: AT URIs of the posts, at most 25. Sent as repeated `uris` query parameters.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-posts)
    """
    return await self.request(
      Request(uris=uris),
      method='GET',
      path='/xrpc/app.bsky.feed.getPosts',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=Posts,
    )
