# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import PostView


class Request(TypedDict):
  """The query, the order and the page."""

  q: str
  """Search string. Lucene-style syntax is accepted."""
  sort: NotRequired[Literal['top', 'latest']]
  """Result order."""
  author: NotRequired[str]
  """Only posts by this account, as a handle or DID."""
  lang: NotRequired[str]
  """Only posts in this language, as a BCP 47 tag."""
  limit: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 25."""
  cursor: NotRequired[str]
  """Opaque page token from the previous response; omit for the first page."""


class PostSearchResults(TypedDict):
  """One page of matching posts."""

  cursor: NotRequired[str]
  """Token for the next page; absent on the last one."""
  hitsTotal: NotRequired[int]
  """Approximate total number of matches, when the search backend reports one."""
  posts: list[PostView]
  """Matching posts."""


class SearchPosts(Endpoint):
  """Full-text post search, paged by cursor."""

  @overload
  def search_posts_paged(
    self,
    *,
    q: str,
    sort: Literal['top', 'latest'] | None = None,
    author: str | None = None,
    lang: str | None = None,
    limit: int | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def search_posts_paged(
    self,
    *,
    q: str,
    sort: Literal['top', 'latest'] | None = None,
    author: str | None = None,
    lang: str | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[PostView, str]: ...
  def search_posts_paged(
    self,
    *,
    q: str,
    sort: Literal['top', 'latest'] | None = None,
    author: str | None = None,
    lang: str | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[PostView, str]:
    """Full-text post search, paged by cursor.

    Paged variant of `search_posts`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      q: Search string. Lucene-style syntax is accepted.
      sort: Result order.
      author: Only posts by this account, as a handle or DID.
      lang: Only posts in this language, as a BCP 47 tag.
      limit: Rows per page. Range [1, 100]; defaults to 25.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-search-posts)
    """

    async def next(cursor: str) -> tuple[list[PostView], str | None]:
      response = await self.search_posts(
        q=q,
        sort=sort,
        author=author,
        lang=lang,
        limit=limit,
        cursor=(cursor or None),
        validate=validate,
      )
      rows = response.get('posts')
      state = response.get('cursor')
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def search_posts(
    self,
    *,
    q: str,
    sort: Literal['top', 'latest'] | None = None,
    author: str | None = None,
    lang: str | None = None,
    limit: int | None = None,
    cursor: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def search_posts(
    self,
    *,
    q: str,
    sort: Literal['top', 'latest'] | None = None,
    author: str | None = None,
    lang: str | None = None,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> PostSearchResults: ...
  async def search_posts(
    self,
    *,
    q: str,
    sort: Literal['top', 'latest'] | None = None,
    author: str | None = None,
    lang: str | None = None,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> PostSearchResults:
    """Full-text post search, paged by cursor.

    Args:
      q: Search string. Lucene-style syntax is accepted.
      sort: Result order.
      author: Only posts by this account, as a handle or DID.
      lang: Only posts in this language, as a BCP 47 tag.
      limit: Rows per page. Range [1, 100]; defaults to 25.
      cursor: Opaque page token from the previous response; omit for the first page.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-search-posts)
    """
    request: Request = Request(q=q)
    if sort is not None:
      request['sort'] = sort
    if author is not None:
      request['author'] = author
    if lang is not None:
      request['lang'] = lang
    if limit is not None:
      request['limit'] = limit
    if cursor is not None:
      request['cursor'] = cursor
    return await self.request(
      request,
      method='GET',
      path='/xrpc/app.bsky.feed.searchPosts',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=PostSearchResults,
    )
