//! Generated by truewire — do not edit by hand.
//!
//! Shapes shared by two or more endpoints, generated from `spec/schemas.json`.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use truewire_core::{serde_json, TimestampIso};

/// Width and height of a media item, as a ratio.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AspectRatio {
    /// Width.
    pub width: i64,
    /// Height.
    pub height: i64,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The annotated byte range of `text`, UTF-8, end exclusive.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ByteSlice {
    /// First byte of the range.
    #[serde(rename = "byteStart")]
    pub byte_start: i64,
    /// Byte after the last byte of the range.
    #[serde(rename = "byteEnd")]
    pub byte_end: i64,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The link card.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExternalLink {
    /// The linked URL.
    pub uri: String,
    /// Card title.
    pub title: String,
    /// Card description.
    pub description: String,
    /// URL of the card image, when there is one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumb: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One feature, tagged by `$type`. The other fields depend on the tag and are kept as they came.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FacetFeature {
    /// Feature type: `app.bsky.richtext.facet#mention`, `#link` or `#tag`.
    #[serde(rename = "$type")]
    pub type_: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A moderation label applied to an account or a record (`com.atproto.label.defs#label`). Only the fields every label carries are declared.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Label {
    /// Label schema version.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ver: Option<i64>,
    /// DID of the labeler that applied the label.
    pub src: String,
    /// AT URI of the labeled record, or the DID of the labeled account.
    pub uri: String,
    /// CID of the labeled record version, when the label is version-specific.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
    /// The label value, such as `porn` or `!hide`.
    pub val: String,
    /// Whether this label negates an earlier label with the same `src`, `uri` and `val`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub neg: Option<bool>,
    /// When the label was created.
    pub cts: TimestampIso,
    /// When the label expires, if it does.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exp: Option<TimestampIso>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NotFoundPostType {
    #[serde(rename = "app.bsky.feed.defs#notFoundPost")]
    AppBskyFeedDefsNotFoundPost,
}

/// A post that does not exist or was deleted (`app.bsky.feed.defs#notFoundPost`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NotFoundPost {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: NotFoundPostType,
    /// AT URI that was asked for.
    pub uri: String,
    /// Always `true`.
    #[serde(rename = "notFound")]
    pub not_found: bool,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ReasonPinType {
    #[serde(rename = "app.bsky.feed.defs#reasonPin")]
    AppBskyFeedDefsReasonPin,
}

/// The post is pinned to the profile (`app.bsky.feed.defs#reasonPin`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ReasonPin {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ReasonPinType,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The embed as written in the record (images, external link, quoted record, video), tagged by `$type`. Kept as it came; the hydrated `embed` on the post view is the typed one.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RecordEmbed {
    /// Embed type, such as `app.bsky.embed.images`.
    #[serde(rename = "$type")]
    pub type_: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RecordViewType {
    #[serde(rename = "app.bsky.embed.record#view")]
    AppBskyEmbedRecordView,
}

/// Hydrated quote of another record (`app.bsky.embed.record#view`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecordView {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: RecordViewType,
    /// The quoted record's view, tagged by `$type`: a post (`#viewRecord`), a not-found, blocked or detached marker, or a feed generator, list, labeler or starter pack view. Kept as a map.
    pub record: HashMap<String, serde_json::Value>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A reference to a specific version of a record: its AT URI and the CID of that version (`com.atproto.repo.strongRef`).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StrongRef {
    /// AT URI of the record (`at://<did>/<collection>/<rkey>`).
    pub uri: String,
    /// CID of the referenced record version.
    pub cid: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// An embed whose `$type` this spec does not model, kept so one unknown embed does not fail the page it arrived on (`app.bsky.embed.gallery#view` appeared in a feed while this client was being written). Only the tag survives validation; the payload is dropped, and `validate=False` returns it whole.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UnknownEmbedView {
    /// Embed type, such as `app.bsky.embed.gallery#view`.
    #[serde(rename = "$type")]
    pub type_: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The relationship between the authenticated viewer and this account (`app.bsky.actor.defs#viewerState`). Without credentials the public AppView sends an empty or absent object.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ViewerState {
    /// Whether the viewer has muted this account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub muted: Option<bool>,
    /// The list through which the account is muted, when it is (`app.bsky.graph.defs#listViewBasic`). Kept as a map.
    #[serde(
        rename = "mutedByList",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub muted_by_list: Option<HashMap<String, serde_json::Value>>,
    /// Whether this account blocks the viewer.
    #[serde(rename = "blockedBy", default, skip_serializing_if = "Option::is_none")]
    pub blocked_by: Option<bool>,
    /// AT URI of the viewer's block record against this account, when there is one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blocking: Option<String>,
    /// The list through which the account is blocked, when it is (`app.bsky.graph.defs#listViewBasic`). Kept as a map.
    #[serde(
        rename = "blockingByList",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub blocking_by_list: Option<HashMap<String, serde_json::Value>>,
    /// AT URI of the viewer's follow record for this account, when there is one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub following: Option<String>,
    /// AT URI of this account's follow record for the viewer, when there is one.
    #[serde(
        rename = "followedBy",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub followed_by: Option<String>,
    /// Followers of this account the viewer also follows (`app.bsky.actor.defs#knownFollowers`). Kept as a map.
    #[serde(
        rename = "knownFollowers",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub known_followers: Option<HashMap<String, serde_json::Value>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The hidden post's author, reduced to its DID.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockedAuthor {
    /// The author's DID.
    pub did: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<ViewerState>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ExternalViewType {
    #[serde(rename = "app.bsky.embed.external#view")]
    AppBskyEmbedExternalView,
}

/// Hydrated external-link card (`app.bsky.embed.external#view`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExternalView {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ExternalViewType,
    pub external: ExternalLink,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A rich-text annotation over a byte range of `text` (`app.bsky.richtext.facet`): a mention, a link or a hashtag.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Facet {
    pub index: ByteSlice,
    /// What the range is: one of `#mention` (`did`), `#link` (`uri`) or `#tag` (`tag`), each tagged by `$type`.
    pub features: Vec<FacetFeature>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One image with its CDN URLs.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageView {
    /// URL of the thumbnail.
    pub thumb: String,
    /// URL of the full-size image.
    pub fullsize: String,
    /// Alt text; empty when none was given.
    pub alt: String,
    #[serde(
        rename = "aspectRatio",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub aspect_ratio: Option<AspectRatio>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A profile as listed in search results and follow graphs (`app.bsky.actor.defs#profileView`).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileView {
    /// The account's DID, its permanent identifier.
    pub did: String,
    /// The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve.
    pub handle: String,
    /// Display name, when set.
    #[serde(
        rename = "displayName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<String>,
    /// URL of the avatar image, when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    /// Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associated: Option<HashMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<ViewerState>,
    /// Moderation labels on the account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<Label>>,
    /// When the account was created.
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampIso>,
    /// Profile bio, when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// When the AppView last indexed the profile record.
    #[serde(rename = "indexedAt", default, skip_serializing_if = "Option::is_none")]
    pub indexed_at: Option<TimestampIso>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The smallest profile view, embedded as an author in posts (`app.bsky.actor.defs#profileViewBasic`).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileViewBasic {
    /// The account's DID, its permanent identifier.
    pub did: String,
    /// The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve.
    pub handle: String,
    /// Display name, when set.
    #[serde(
        rename = "displayName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<String>,
    /// URL of the avatar image, when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    /// Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associated: Option<HashMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<ViewerState>,
    /// Moderation labels on the account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<Label>>,
    /// When the account was created.
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampIso>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A full profile with counts (`app.bsky.actor.defs#profileViewDetailed`).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileViewDetailed {
    /// The account's DID, its permanent identifier.
    pub did: String,
    /// The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve.
    pub handle: String,
    /// Display name, when set.
    #[serde(
        rename = "displayName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<String>,
    /// URL of the avatar image, when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    /// Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associated: Option<HashMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<ViewerState>,
    /// Moderation labels on the account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<Label>>,
    /// When the account was created.
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampIso>,
    /// Profile bio, when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URL of the banner image, when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub banner: Option<String>,
    /// Number of accounts following this one.
    #[serde(
        rename = "followersCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub followers_count: Option<i64>,
    /// Number of accounts this one follows.
    #[serde(
        rename = "followsCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub follows_count: Option<i64>,
    /// Number of posts by this account.
    #[serde(
        rename = "postsCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub posts_count: Option<i64>,
    /// When the AppView last indexed the profile record.
    #[serde(rename = "indexedAt", default, skip_serializing_if = "Option::is_none")]
    pub indexed_at: Option<TimestampIso>,
    #[serde(
        rename = "pinnedPost",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pinned_post: Option<StrongRef>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Which thread the post replies into, when it is a reply.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReplyRef {
    pub root: StrongRef,
    pub parent: StrongRef,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum VideoViewType {
    #[serde(rename = "app.bsky.embed.video#view")]
    AppBskyEmbedVideoView,
}

/// Hydrated video embed (`app.bsky.embed.video#view`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VideoView {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: VideoViewType,
    /// CID of the video blob.
    pub cid: String,
    /// URL of the HLS playlist.
    pub playlist: String,
    /// URL of the poster image, when there is one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
    /// Alt text, when given.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alt: Option<String>,
    #[serde(
        rename = "aspectRatio",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub aspect_ratio: Option<AspectRatio>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BlockedPostType {
    #[serde(rename = "app.bsky.feed.defs#blockedPost")]
    AppBskyFeedDefsBlockedPost,
}

/// A post hidden by a block between the viewer and its author (`app.bsky.feed.defs#blockedPost`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BlockedPost {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: BlockedPostType,
    /// AT URI of the hidden post.
    pub uri: String,
    /// Always `true`.
    pub blocked: bool,
    pub author: BlockedAuthor,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ImagesViewType {
    #[serde(rename = "app.bsky.embed.images#view")]
    AppBskyEmbedImagesView,
}

/// Hydrated image embed (`app.bsky.embed.images#view`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ImagesView {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ImagesViewType,
    /// The images, in order.
    pub images: Vec<ImageView>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PostRecordType {
    #[serde(rename = "app.bsky.feed.post")]
    AppBskyFeedPost,
}

/// The post record as its author wrote it (`app.bsky.feed.post`). An open object: the fields declared here are the ones every post carries plus the common optional ones; a client may put more in.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PostRecord {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: PostRecordType,
    /// The post text, at most 300 graphemes.
    pub text: String,
    /// When the author's client says the post was written. Client-supplied, unlike `indexedAt` on the view.
    #[serde(rename = "createdAt")]
    pub created_at: TimestampIso,
    /// BCP 47 language tags of the text, when the client set them.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub langs: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reply: Option<ReplyRef>,
    /// Rich-text annotations over `text`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub facets: Option<Vec<Facet>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embed: Option<RecordEmbed>,
    /// Additional hashtags, outside the text.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ReasonRepostType {
    #[serde(rename = "app.bsky.feed.defs#reasonRepost")]
    AppBskyFeedDefsReasonRepost,
}

/// The post was reposted by `by` (`app.bsky.feed.defs#reasonRepost`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ReasonRepost {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ReasonRepostType,
    pub by: ProfileViewBasic,
    /// When the repost was indexed.
    #[serde(rename = "indexedAt")]
    pub indexed_at: TimestampIso,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RecordWithMediaViewType {
    #[serde(rename = "app.bsky.embed.recordWithMedia#view")]
    AppBskyEmbedRecordWithMediaView,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecordWithMediaViewMedia {
    ImagesView(ImagesView),
    ExternalView(ExternalView),
    VideoView(VideoView),
}

/// A quote with media attached (`app.bsky.embed.recordWithMedia#view`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecordWithMediaView {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: RecordWithMediaViewType,
    pub record: RecordView,
    /// The attached media, tagged by `$type`.
    pub media: RecordWithMediaViewMedia,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EmbedView {
    ImagesView(ImagesView),
    ExternalView(ExternalView),
    VideoView(VideoView),
    RecordView(RecordView),
    RecordWithMediaView(RecordWithMediaView),
    UnknownEmbedView(UnknownEmbedView),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostViewEmbed {
    ImagesView(ImagesView),
    ExternalView(ExternalView),
    VideoView(VideoView),
    RecordView(RecordView),
    RecordWithMediaView(RecordWithMediaView),
    UnknownEmbedView(UnknownEmbedView),
}

/// A post as the AppView serves it: the record plus its author, counts and hydrated embed (`app.bsky.feed.defs#postView`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PostView {
    /// AT URI of the post.
    pub uri: String,
    /// CID of the post record version.
    pub cid: String,
    pub author: ProfileViewBasic,
    pub record: PostRecord,
    /// The hydrated embed of a post, tagged by `$type` (`app.bsky.embed.*#view`). The union is open: a tag none of the modelled members carries validates as `UnknownEmbedView` rather than failing the post.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embed: Option<PostViewEmbed>,
    /// Number of replies.
    #[serde(
        rename = "replyCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reply_count: Option<i64>,
    /// Number of reposts.
    #[serde(
        rename = "repostCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub repost_count: Option<i64>,
    /// Number of likes.
    #[serde(rename = "likeCount", default, skip_serializing_if = "Option::is_none")]
    pub like_count: Option<i64>,
    /// Number of quote posts.
    #[serde(
        rename = "quoteCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quote_count: Option<i64>,
    /// When the AppView indexed this version of the post.
    #[serde(rename = "indexedAt")]
    pub indexed_at: TimestampIso,
    /// The viewer's own like, repost and mute state on the post (`app.bsky.feed.defs#viewerState`). Kept as a map; empty without credentials.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<HashMap<String, serde_json::Value>>,
    /// Moderation labels on the post.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<Label>>,
    /// The thread's reply gate, when the root post has one (`app.bsky.feed.defs#threadgateView`). Kept as a map.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub threadgate: Option<HashMap<String, serde_json::Value>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FeedReplyRefRoot {
    PostView(PostView),
    NotFoundPost(NotFoundPost),
    BlockedPost(BlockedPost),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FeedReplyRefParent {
    PostView(PostView),
    NotFoundPost(NotFoundPost),
    BlockedPost(BlockedPost),
}

/// The thread context of a reply (`app.bsky.feed.defs#replyRef`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeedReplyRef {
    /// A post referenced from a reply chain: the post view, or a marker that it is gone or blocked.
    pub root: FeedReplyRefRoot,
    /// A post referenced from a reply chain: the post view, or a marker that it is gone or blocked.
    pub parent: FeedReplyRefParent,
    #[serde(
        rename = "grandparentAuthor",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub grandparent_author: Option<ProfileViewBasic>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReplyRefPost {
    PostView(PostView),
    NotFoundPost(NotFoundPost),
    BlockedPost(BlockedPost),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ThreadPostItemAnyOf0Type {
    #[serde(rename = "app.bsky.feed.defs#threadViewPost")]
    AppBskyFeedDefsThreadViewPost,
}

/// A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThreadPostItemAnyOf0 {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ThreadPostItemAnyOf0Type,
    pub post: PostView,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ThreadPostParentAnyOf0Type {
    #[serde(rename = "app.bsky.feed.defs#threadViewPost")]
    AppBskyFeedDefsThreadViewPost,
}

/// A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThreadPostParentAnyOf0 {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ThreadPostParentAnyOf0Type,
    pub post: PostView,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ThreadPostThreadNodeAnyOf0Type {
    #[serde(rename = "app.bsky.feed.defs#threadViewPost")]
    AppBskyFeedDefsThreadViewPost,
}

/// A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThreadPostThreadNodeAnyOf0 {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ThreadPostThreadNodeAnyOf0Type,
    pub post: PostView,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FeedViewPostReason {
    ReasonRepost(ReasonRepost),
    ReasonPin(ReasonPin),
}

/// One feed entry: a post, plus why it is in the feed (`app.bsky.feed.defs#feedViewPost`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeedViewPost {
    pub post: PostView,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reply: Option<FeedReplyRef>,
    /// Why the post is in the feed when it is not the author's own: a repost, or a pin.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<FeedViewPostReason>,
    /// Opaque context from the feed generator, to echo back in interaction reports.
    #[serde(
        rename = "feedContext",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub feed_context: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ThreadNode {
    ThreadPostThreadNodeAnyOf0(ThreadPostThreadNodeAnyOf0),
    NotFoundPost(NotFoundPost),
    BlockedPost(BlockedPost),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ThreadViewPostType {
    #[serde(rename = "app.bsky.feed.defs#threadViewPost")]
    AppBskyFeedDefsThreadViewPost,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ThreadViewPostParent {
    ThreadPostParentAnyOf0(ThreadPostParentAnyOf0),
    NotFoundPost(NotFoundPost),
    BlockedPost(BlockedPost),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ThreadViewPostRepliesItem {
    ThreadPostItemAnyOf0(ThreadPostItemAnyOf0),
    NotFoundPost(NotFoundPost),
    BlockedPost(BlockedPost),
}

/// The requested post with its ancestors and replies (`app.bsky.feed.defs#threadViewPost`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThreadViewPost {
    /// Lexicon type tag of this object.
    #[serde(rename = "$type")]
    pub type_: ThreadViewPostType,
    pub post: PostView,
    /// A parent or reply in a thread: the post, or a marker that it is gone or blocked. Its own `parent` and `replies` are not typed here, so a validated thread keeps one level around the root; `validate=False` returns the whole tree.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<ThreadViewPostParent>,
    /// Direct replies, when `depth` allowed them.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replies: Option<Vec<ThreadViewPostRepliesItem>>,
    /// The thread's reply gate, when the root has one (`app.bsky.feed.defs#threadgateView`). Kept as a map.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub threadgate: Option<HashMap<String, serde_json::Value>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}
