// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type StreamEndpoint, type Subscription, type TimestampIso, type TimestampMicros, t } from '@truewire/core'

/** An account status change; present when `kind` is `account`. */
export interface AccountStatus {
  /** Whether the account is active on its host. */
  active: boolean
  /** The account's DID. */
  did: string
  /** Sequence number on the upstream firehose. */
  seq: number
  /** When the change happened. */
  time: TimestampIso
  /** Why the account is inactive, when it is: `takendown`, `suspended`, `deleted` or `deactivated`. */
  status?: string
}

export const AccountStatus: Codec<AccountStatus> = t.object({
  active: t.boolean,
  did: t.string,
  seq: t.integer,
  time: t.dateTime,
  status: t.optional(t.string),
})

/** One record operation in the repository; present when `kind` is `commit`. */
export interface Commit {
  /** Repository revision after this commit. */
  rev: string
  /** What happened to the record. */
  operation: 'create' | 'update' | 'delete'
  /** Collection NSID of the record, such as `app.bsky.feed.post`. */
  collection: string
  /** Record key within the collection. */
  rkey: string
  /** The record, for `create` and `update`; absent on `delete`. Any collection's record, so kept as a map: `$type` names the lexicon. */
  record?: Record<string, unknown>
  /** CID of the record, for `create` and `update`; absent on `delete`. */
  cid?: string
}

export const Commit: Codec<Commit> = t.object({
  rev: t.string,
  operation: t.literal('create', 'update', 'delete'),
  collection: t.string,
  rkey: t.string,
  record: t.optional(t.record(t.unknown)),
  cid: t.optional(t.string),
})

/** An identity change; present when `kind` is `identity`. */
export interface Identity {
  /** The DID whose identity changed. */
  did: string
  /** The current handle, when it resolved. */
  handle?: string
  /** Sequence number on the upstream firehose. */
  seq: number
  /** When the change happened. */
  time: TimestampIso
}

export const Identity: Codec<Identity> = t.object({
  did: t.string,
  handle: t.optional(t.string),
  seq: t.integer,
  time: t.dateTime,
})

/** The filter and the starting point, sent as the connection URL's query string. */
export interface Parameters {
  /** Collection NSIDs to include, such as `app.bsky.feed.post`; a trailing `.*` matches a prefix (`app.bsky.graph.*`). At most 100. Omit for every collection. Sent as repeated `wantedCollections` query parameters. */
  wantedCollections?: string[]
  /** DIDs to include, at most 10000. Omit for every account. Sent as repeated `wantedDids` query parameters. */
  wantedDids?: string[]
  /** Replay from this instant, as Unix microseconds on the wire; omit to start from now. Jetstream keeps a bounded backlog, and a cursor before it starts from the oldest event kept. */
  cursor?: TimestampMicros
}

export const Parameters: Codec<Parameters> = t.object({
  wantedCollections: t.optional(t.array(t.string)),
  wantedDids: t.optional(t.array(t.string)),
  cursor: t.optional(t.epochMicros),
})

/** One event. `kind` says which of `commit`, `identity` and `account` is present. */
export interface JetstreamEvent {
  /** DID of the repository the event is about. */
  did: string
  /** When the event was emitted, as Unix microseconds on the wire. Also the cursor to resume from. */
  time_us: TimestampMicros
  /** Event kind: a repository commit, an identity (handle or DID document) change, or an account status change. */
  kind: 'commit' | 'identity' | 'account'
  commit?: Commit
  identity?: Identity
  account?: AccountStatus
}

export const JetstreamEvent: Codec<JetstreamEvent> = t.object({
  did: t.string,
  time_us: t.epochMicros,
  kind: t.literal('commit', 'identity', 'account'),
  commit: t.optional(Commit),
  identity: t.optional(Identity),
  account: t.optional(AccountStatus),
})

/** Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open. */
export class Events {
  constructor(readonly core: StreamEndpoint) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  events(parameters: Parameters, options: CallOptions & { validate: false }): Subscription<unknown>
  /**
   * Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open.
   *
   * @see https://github.com/bluesky-social/jetstream#consuming-jetstream
   */
  events(parameters?: Parameters, options?: CallOptions): Subscription<JetstreamEvent>
  events(parameters?: Parameters, options?: CallOptions): Subscription<JetstreamEvent> {
    return this.core.subscribe({
      channel: 'subscribe',
      parameters: parameters ?? {},
      parametersCodec: Parameters,
      messageCodec: JetstreamEvent,
      meta: {},
      ...options,
    })
  }
}
