//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use truewire_core::{HttpEndpoint, StreamEndpoint};

use crate::actor::Actor;
use crate::feed::Feed;
use crate::graph::Graph;
use crate::identity::Identity;
use crate::jetstream::Jetstream;
use crate::meta::DefaultMeta;

/// Bluesky: profiles, feeds, threads, the social graph and handle resolution from the public AppView, plus the Jetstream firehose of repository events. No credentials needed.
///
/// See <https://docs.bsky.app/docs/get-started>.
#[derive(Clone)]
pub struct Bluesky {
    /// Profiles: one, several, or by search (`app.bsky.actor.*`).
    pub actor: Actor,
    /// Posts, threads and feeds (`app.bsky.feed.*`).
    pub feed: Feed,
    /// The social graph: who follows whom (`app.bsky.graph.*`).
    pub graph: Graph,
    /// Handle resolution (`com.atproto.identity.*`).
    pub identity: Identity,
    /// Jetstream: Bluesky's JSON firehose of repository commits, identity changes and account status changes, over one WebSocket per subscription.
    pub jetstream: Jetstream,
}

impl Bluesky {
    pub fn new(client: Arc<dyn HttpEndpoint<DefaultMeta>>, socket: Arc<dyn StreamEndpoint>) -> Self {
        Self {
            actor: Actor::new(client.clone()),
            feed: Feed::new(client.clone()),
            graph: Graph::new(client.clone()),
            identity: Identity::new(client),
            jetstream: Jetstream::new(socket),
        }
    }
}
