// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { BlockedPost, NotFoundPost, ThreadViewPost } from '../types/index.js'

/** Which post and how much of its thread. */
export interface Request {
  /** AT URI of the post, such as `at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.feed.post/3kxyz...`. */
  uri: string
  /** How many levels of replies to include. Range [0, 1000]; defaults to 6. */
  depth?: number
  /** How many ancestors to include. Range [0, 1000]; defaults to 80. */
  parentHeight?: number
}

export const Request: Codec<Request> = t.object({
  uri: t.string,
  depth: t.optional(t.integer),
  parentHeight: t.optional(t.integer),
})

/** The thread around the requested post. */
export interface PostThread {
  /** The requested post with its context, or a marker that it is gone or blocked. */
  thread: ThreadViewPost | NotFoundPost | BlockedPost
  /** The thread's reply gate, when the root has one (`app.bsky.feed.defs#threadgateView`). Kept as a map. */
  threadgate?: Record<string, unknown>
}

export const PostThread: Codec<PostThread> = t.object({
  thread: t.union(ThreadViewPost, NotFoundPost, BlockedPost),
  threadgate: t.optional(t.record(t.unknown)),
})

/** A post with its ancestors and replies. */
export class GetPostThread {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getPostThread(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * A post with its ancestors and replies.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-post-thread
   */
  getPostThread(request: Request, options?: CallOptions): Promise<PostThread>
  async getPostThread(request: Request, options?: CallOptions): Promise<PostThread> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.feed.getPostThread',
      request,
      requestCodec: Request,
      responseCodec: PostThread,
      meta: { public: true },
      ...options,
    })
  }
}
