// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { PostView } from '../types/index.js'

/** Which posts. */
export interface Request {
  /** AT URIs of the posts, at most 25. Sent as repeated `uris` query parameters. */
  uris: string[]
}

export const Request: Codec<Request> = t.object({
  uris: t.array(t.string),
})

/** The posts that exist, in the order asked for. */
export interface Posts {
  /** The posts. */
  posts: PostView[]
}

export const Posts: Codec<Posts> = t.object({
  posts: t.array(PostView),
})

/** Get up to 25 posts by AT URI in one call. */
export class GetPosts {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getPosts(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get up to 25 posts by AT URI in one call.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-posts
   */
  getPosts(request: Request, options?: CallOptions): Promise<Posts>
  async getPosts(request: Request, options?: CallOptions): Promise<Posts> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.feed.getPosts',
      request,
      requestCodec: Request,
      responseCodec: Posts,
      meta: { public: true },
      ...options,
    })
  }
}
