// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, PaginatedResponse, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { FeedViewPost } from '../types/index.js'

/** Which feed and which page. */
export interface Request {
  /** AT URI of the feed generator record (`app.bsky.feed.generator`). */
  feed: string
  /** Rows per page. Range [1, 100]; defaults to 50. */
  limit?: number
  /** Opaque page token from the previous response; omit for the first page. */
  cursor?: string
}

export const Request: Codec<Request> = t.object({
  feed: t.string,
  limit: t.optional(t.integer),
  cursor: t.optional(t.string),
})

/** One page of the feed. */
export interface Feed {
  /** Token for the next page; absent on the last one. */
  cursor?: string
  /** Feed entries, in the generator's order. */
  feed: FeedViewPost[]
}

export const Feed: Codec<Feed> = t.object({
  cursor: t.optional(t.string),
  feed: t.array(FeedViewPost),
})

/** `getFeedPaged`'s request: `Request` without `cursor`, which the walk advances. */
export type GetFeedPagedRequest = Omit<Request, 'cursor'>

/** A custom feed, served through its feed generator, paged by cursor. */
export class GetFeed {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFeedPaged(request: GetFeedPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * A custom feed, served through its feed generator, paged by cursor.
   *
   * Paged variant of `getFeed`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-feed
   */
  getFeedPaged(request: GetFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string>
  getFeedPaged(request: GetFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string> {
    const next = async (cursor: string): Promise<[FeedViewPost[], string | null]> => {
      const response = await this.getFeed({ ...request, cursor: cursor || undefined }, options)
      const rows = response.feed ?? []
      const following = response.cursor ?? null
      return [rows, following || null]
    }
    return new PaginatedResponse('', next)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFeed(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * A custom feed, served through its feed generator, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-feed
   */
  getFeed(request: Request, options?: CallOptions): Promise<Feed>
  async getFeed(request: Request, options?: CallOptions): Promise<Feed> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.feed.getFeed',
      request,
      requestCodec: Request,
      responseCodec: Feed,
      meta: { public: true },
      ...options,
    })
  }
}
