// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, PaginatedResponse, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { FeedViewPost } from '../types/index.js'

/** Whose feed, which posts, which page. */
export interface Request {
  /** Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`. */
  actor: string
  /** Rows per page. Range [1, 100]; defaults to 50. */
  limit?: number
  /** Opaque page token from the previous response; omit for the first page. */
  cursor?: string
  /** Which posts to include. */
  filter?: 'posts_with_replies' | 'posts_no_replies' | 'posts_with_media' | 'posts_and_author_threads'
}

export const Request: Codec<Request> = t.object({
  actor: t.string,
  limit: t.optional(t.integer),
  cursor: t.optional(t.string),
  filter: t.optional(t.literal('posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads')),
})

/** One page of the feed. */
export interface AuthorFeed {
  /** Token for the next page; absent on the last one. */
  cursor?: string
  /** Feed entries, newest first. */
  feed: FeedViewPost[]
}

export const AuthorFeed: Codec<AuthorFeed> = t.object({
  cursor: t.optional(t.string),
  feed: t.array(FeedViewPost),
})

/** `getAuthorFeedPaged`'s request: `Request` without `cursor`, which the walk advances. */
export type GetAuthorFeedPagedRequest = Omit<Request, 'cursor'>

/** An account's posts and reposts, newest first, paged by cursor. */
export class GetAuthorFeed {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getAuthorFeedPaged(request: GetAuthorFeedPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * An account's posts and reposts, newest first, paged by cursor.
   *
   * Paged variant of `getAuthorFeed`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed
   */
  getAuthorFeedPaged(request: GetAuthorFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string>
  getAuthorFeedPaged(request: GetAuthorFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string> {
    const next = async (cursor: string): Promise<[FeedViewPost[], string | null]> => {
      const response = await this.getAuthorFeed({ ...request, cursor: cursor || undefined }, options)
      const rows = response.feed ?? []
      const following = response.cursor ?? null
      return [rows, following || null]
    }
    return new PaginatedResponse('', next)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getAuthorFeed(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * An account's posts and reposts, newest first, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed
   */
  getAuthorFeed(request: Request, options?: CallOptions): Promise<AuthorFeed>
  async getAuthorFeed(request: Request, options?: CallOptions): Promise<AuthorFeed> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.feed.getAuthorFeed',
      request,
      requestCodec: Request,
      responseCodec: AuthorFeed,
      meta: { public: true },
      ...options,
    })
  }
}
