// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint, PaginatedResponse } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { FeedViewPost, PostView } from '../types/index.js'
import * as getAuthorFeed from './get_author_feed.js'
import * as getFeed from './get_feed.js'
import * as getPostThread from './get_post_thread.js'
import * as getPosts from './get_posts.js'
import * as searchPosts from './search_posts.js'

/**
 * Posts, threads and feeds (`app.bsky.feed.*`).
 *
 * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed
 */
export class Feed {
  private readonly getAuthorFeed_: getAuthorFeed.GetAuthorFeed
  private readonly getFeed_: getFeed.GetFeed
  private readonly getPostThread_: getPostThread.GetPostThread
  private readonly getPosts_: getPosts.GetPosts
  private readonly searchPosts_: searchPosts.SearchPosts

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.getAuthorFeed_ = new getAuthorFeed.GetAuthorFeed(core)
    this.getFeed_ = new getFeed.GetFeed(core)
    this.getPostThread_ = new getPostThread.GetPostThread(core)
    this.getPosts_ = new getPosts.GetPosts(core)
    this.searchPosts_ = new searchPosts.SearchPosts(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getAuthorFeedPaged(request: getAuthorFeed.GetAuthorFeedPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * An account's posts and reposts, newest first, paged by cursor.
   *
   * Paged variant of `getAuthorFeed`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed
   */
  getAuthorFeedPaged(request: getAuthorFeed.GetAuthorFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string>
  getAuthorFeedPaged(request: getAuthorFeed.GetAuthorFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string> {
    return this.getAuthorFeed_.getAuthorFeedPaged(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getAuthorFeed(request: getAuthorFeed.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * An account's posts and reposts, newest first, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed
   */
  getAuthorFeed(request: getAuthorFeed.Request, options?: CallOptions): Promise<getAuthorFeed.AuthorFeed>
  getAuthorFeed(request: getAuthorFeed.Request, options?: CallOptions): Promise<getAuthorFeed.AuthorFeed> {
    return this.getAuthorFeed_.getAuthorFeed(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFeedPaged(request: getFeed.GetFeedPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * A custom feed, served through its feed generator, paged by cursor.
   *
   * Paged variant of `getFeed`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-feed
   */
  getFeedPaged(request: getFeed.GetFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string>
  getFeedPaged(request: getFeed.GetFeedPagedRequest, options?: CallOptions): PaginatedResponse<FeedViewPost, string> {
    return this.getFeed_.getFeedPaged(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getFeed(request: getFeed.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * A custom feed, served through its feed generator, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-feed
   */
  getFeed(request: getFeed.Request, options?: CallOptions): Promise<getFeed.Feed>
  getFeed(request: getFeed.Request, options?: CallOptions): Promise<getFeed.Feed> {
    return this.getFeed_.getFeed(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getPostThread(request: getPostThread.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * A post with its ancestors and replies.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-post-thread
   */
  getPostThread(request: getPostThread.Request, options?: CallOptions): Promise<getPostThread.PostThread>
  getPostThread(request: getPostThread.Request, options?: CallOptions): Promise<getPostThread.PostThread> {
    return this.getPostThread_.getPostThread(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getPosts(request: getPosts.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get up to 25 posts by AT URI in one call.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-get-posts
   */
  getPosts(request: getPosts.Request, options?: CallOptions): Promise<getPosts.Posts>
  getPosts(request: getPosts.Request, options?: CallOptions): Promise<getPosts.Posts> {
    return this.getPosts_.getPosts(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchPostsPaged(request: searchPosts.SearchPostsPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Full-text post search, paged by cursor.
   *
   * Paged variant of `searchPosts`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-search-posts
   */
  searchPostsPaged(request: searchPosts.SearchPostsPagedRequest, options?: CallOptions): PaginatedResponse<PostView, string>
  searchPostsPaged(request: searchPosts.SearchPostsPagedRequest, options?: CallOptions): PaginatedResponse<PostView, string> {
    return this.searchPosts_.searchPostsPaged(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchPosts(request: searchPosts.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Full-text post search, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-search-posts
   */
  searchPosts(request: searchPosts.Request, options?: CallOptions): Promise<searchPosts.PostSearchResults>
  searchPosts(request: searchPosts.Request, options?: CallOptions): Promise<searchPosts.PostSearchResults> {
    return this.searchPosts_.searchPosts(request, options)
  }
}
