// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, PaginatedResponse, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { PostView } from '../types/index.js'

/** The query, the order and the page. */
export interface Request {
  /** Search string. Lucene-style syntax is accepted. */
  q: string
  /** Result order. */
  sort?: 'top' | 'latest'
  /** Only posts by this account, as a handle or DID. */
  author?: string
  /** Only posts in this language, as a BCP 47 tag. */
  lang?: string
  /** Rows per page. Range [1, 100]; defaults to 25. */
  limit?: number
  /** Opaque page token from the previous response; omit for the first page. */
  cursor?: string
}

export const Request: Codec<Request> = t.object({
  q: t.string,
  sort: t.optional(t.literal('top', 'latest')),
  author: t.optional(t.string),
  lang: t.optional(t.string),
  limit: t.optional(t.integer),
  cursor: t.optional(t.string),
})

/** One page of matching posts. */
export interface PostSearchResults {
  /** Token for the next page; absent on the last one. */
  cursor?: string
  /** Approximate total number of matches, when the search backend reports one. */
  hitsTotal?: number
  /** Matching posts. */
  posts: PostView[]
}

export const PostSearchResults: Codec<PostSearchResults> = t.object({
  cursor: t.optional(t.string),
  hitsTotal: t.optional(t.integer),
  posts: t.array(PostView),
})

/** `searchPostsPaged`'s request: `Request` without `cursor`, which the walk advances. */
export type SearchPostsPagedRequest = Omit<Request, 'cursor'>

/** Full-text post search, paged by cursor. */
export class SearchPosts {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchPostsPaged(request: SearchPostsPagedRequest, options: CallOptions & { validate: false }): PaginatedResponse<unknown, string>
  /**
   * Full-text post search, paged by cursor.
   *
   * Paged variant of `searchPosts`: awaitable (flattens every page) or async-iterable (one page at a time).
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-search-posts
   */
  searchPostsPaged(request: SearchPostsPagedRequest, options?: CallOptions): PaginatedResponse<PostView, string>
  searchPostsPaged(request: SearchPostsPagedRequest, options?: CallOptions): PaginatedResponse<PostView, string> {
    const next = async (cursor: string): Promise<[PostView[], string | null]> => {
      const response = await this.searchPosts({ ...request, cursor: cursor || undefined }, options)
      const rows = response.posts ?? []
      const following = response.cursor ?? null
      return [rows, following || null]
    }
    return new PaginatedResponse('', next)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  searchPosts(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Full-text post search, paged by cursor.
   *
   * @see https://docs.bsky.app/docs/api/app-bsky-feed-search-posts
   */
  searchPosts(request: Request, options?: CallOptions): Promise<PostSearchResults>
  async searchPosts(request: Request, options?: CallOptions): Promise<PostSearchResults> {
    return this.core.request({
      method: 'GET',
      path: '/xrpc/app.bsky.feed.searchPosts',
      request,
      requestCodec: Request,
      responseCodec: PostSearchResults,
      meta: { public: true },
      ...options,
    })
  }
}
