# Generated by truewire — do not edit by hand.
from .resolve_handle import ResolveHandle


class Identity(ResolveHandle):
  """Handle resolution (`com.atproto.identity.*`).

  References:
    - [Upstream docs](https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle)
  """
