# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from bluesky.core import Endpoint


class Request(TypedDict):
  """Which handle."""

  handle: str
  """The handle, such as `bsky.app`."""


class ResolvedHandle(TypedDict):
  """The DID the handle currently points at."""

  did: str
  """The DID."""


class ResolveHandle(Endpoint):
  """Resolve a handle to its DID."""

  @overload
  async def resolve_handle(self, handle: str, *, validate: Literal[False]) -> Any: ...
  @overload
  async def resolve_handle(
    self,
    handle: str,
    *,
    validate: bool | None = None,
  ) -> ResolvedHandle: ...
  async def resolve_handle(
    self,
    handle: str,
    *,
    validate: bool | None = None,
  ) -> ResolvedHandle:
    """Resolve a handle to its DID.

    Args:
      handle: The handle, such as `bsky.app`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle)
    """
    return await self.request(
      Request(handle=handle),
      method='GET',
      path='/xrpc/com.atproto.identity.resolveHandle',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=ResolvedHandle,
    )
