// Generated by truewire — do not edit by hand.
/** Shapes shared by two or more endpoints, generated from `spec/schemas.json`. */
import { type Codec, type TimestampIso, t } from '@truewire/core'

/** Width and height of a media item, as a ratio. */
export interface AspectRatio {
  /** Width. */
  width: number
  /** Height. */
  height: number
}

export const AspectRatio: Codec<AspectRatio> = t.object({
  width: t.integer,
  height: t.integer,
})

/** The annotated byte range of `text`, UTF-8, end exclusive. */
export interface ByteSlice {
  /** First byte of the range. */
  byteStart: number
  /** Byte after the last byte of the range. */
  byteEnd: number
}

export const ByteSlice: Codec<ByteSlice> = t.object({
  byteStart: t.integer,
  byteEnd: t.integer,
})

/** The link card. */
export interface ExternalLink {
  /** The linked URL. */
  uri: string
  /** Card title. */
  title: string
  /** Card description. */
  description: string
  /** URL of the card image, when there is one. */
  thumb?: string
}

export const ExternalLink: Codec<ExternalLink> = t.object({
  uri: t.string,
  title: t.string,
  description: t.string,
  thumb: t.optional(t.string),
})

/** One feature, tagged by `$type`. The other fields depend on the tag and are kept as they came. */
export interface FacetFeature {
  /** Feature type: `app.bsky.richtext.facet#mention`, `#link` or `#tag`. */
  $type: string
}

export const FacetFeature: Codec<FacetFeature> = t.object({
  $type: t.string,
})

/** A moderation label applied to an account or a record (`com.atproto.label.defs#label`). Only the fields every label carries are declared. */
export interface Label {
  /** Label schema version. */
  ver?: number
  /** DID of the labeler that applied the label. */
  src: string
  /** AT URI of the labeled record, or the DID of the labeled account. */
  uri: string
  /** CID of the labeled record version, when the label is version-specific. */
  cid?: string
  /** The label value, such as `porn` or `!hide`. */
  val: string
  /** Whether this label negates an earlier label with the same `src`, `uri` and `val`. */
  neg?: boolean
  /** When the label was created. */
  cts: TimestampIso
  /** When the label expires, if it does. */
  exp?: TimestampIso
}

export const Label: Codec<Label> = t.object({
  ver: t.optional(t.integer),
  src: t.string,
  uri: t.string,
  cid: t.optional(t.string),
  val: t.string,
  neg: t.optional(t.boolean),
  cts: t.dateTime,
  exp: t.optional(t.dateTime),
})

/** A post that does not exist or was deleted (`app.bsky.feed.defs#notFoundPost`). */
export interface NotFoundPost {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#notFoundPost'
  /** AT URI that was asked for. */
  uri: string
  /** Always `true`. */
  notFound: true
}

export const NotFoundPost: Codec<NotFoundPost> = t.object({
  $type: t.literal('app.bsky.feed.defs#notFoundPost'),
  uri: t.string,
  notFound: t.literal(true),
})

/** The post is pinned to the profile (`app.bsky.feed.defs#reasonPin`). */
export interface ReasonPin {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#reasonPin'
}

export const ReasonPin: Codec<ReasonPin> = t.object({
  $type: t.literal('app.bsky.feed.defs#reasonPin'),
})

/** The embed as written in the record (images, external link, quoted record, video), tagged by `$type`. Kept as it came; the hydrated `embed` on the post view is the typed one. */
export interface RecordEmbed {
  /** Embed type, such as `app.bsky.embed.images`. */
  $type: string
}

export const RecordEmbed: Codec<RecordEmbed> = t.object({
  $type: t.string,
})

/** Hydrated quote of another record (`app.bsky.embed.record#view`). */
export interface RecordView {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.embed.record#view'
  /** The quoted record's view, tagged by `$type`: a post (`#viewRecord`), a not-found, blocked or detached marker, or a feed generator, list, labeler or starter pack view. Kept as a map. */
  record: Record<string, unknown>
}

export const RecordView: Codec<RecordView> = t.object({
  $type: t.literal('app.bsky.embed.record#view'),
  record: t.record(t.unknown),
})

/** One commit to a repository: every write returns the commit that carried it, which is how a caller orders its own writes against the firehose. */
export interface RepoCommit {
  /** CID of the commit. */
  cid: string
  /** Revision of the repository after it. */
  rev: string
}

export const RepoCommit: Codec<RepoCommit> = t.object({
  cid: t.string,
  rev: t.string,
})

/** A reference to a specific version of a record: its AT URI and the CID of that version (`com.atproto.repo.strongRef`). */
export interface StrongRef {
  /** AT URI of the record (`at://<did>/<collection>/<rkey>`). */
  uri: string
  /** CID of the referenced record version. */
  cid: string
}

export const StrongRef: Codec<StrongRef> = t.object({
  uri: t.string,
  cid: t.string,
})

/** An embed whose `$type` this spec does not model, kept so one unknown embed does not fail the page it arrived on (`app.bsky.embed.gallery#view` appeared in a feed while this client was being written). Only the tag survives validation; the payload is dropped, and `validate=False` returns it whole. */
export interface UnknownEmbedView {
  /** Embed type, such as `app.bsky.embed.gallery#view`. */
  $type: string
}

export const UnknownEmbedView: Codec<UnknownEmbedView> = t.object({
  $type: t.string,
})

/** The relationship between the authenticated viewer and this account (`app.bsky.actor.defs#viewerState`). Without credentials the public AppView sends an empty or absent object. */
export interface ViewerState {
  /** Whether the viewer has muted this account. */
  muted?: boolean
  /** The list through which the account is muted, when it is (`app.bsky.graph.defs#listViewBasic`). Kept as a map. */
  mutedByList?: Record<string, unknown>
  /** Whether this account blocks the viewer. */
  blockedBy?: boolean
  /** AT URI of the viewer's block record against this account, when there is one. */
  blocking?: string
  /** The list through which the account is blocked, when it is (`app.bsky.graph.defs#listViewBasic`). Kept as a map. */
  blockingByList?: Record<string, unknown>
  /** AT URI of the viewer's follow record for this account, when there is one. */
  following?: string
  /** AT URI of this account's follow record for the viewer, when there is one. */
  followedBy?: string
  /** Followers of this account the viewer also follows (`app.bsky.actor.defs#knownFollowers`). Kept as a map. */
  knownFollowers?: Record<string, unknown>
}

export const ViewerState: Codec<ViewerState> = t.object({
  muted: t.optional(t.boolean),
  mutedByList: t.optional(t.record(t.unknown)),
  blockedBy: t.optional(t.boolean),
  blocking: t.optional(t.string),
  blockingByList: t.optional(t.record(t.unknown)),
  following: t.optional(t.string),
  followedBy: t.optional(t.string),
  knownFollowers: t.optional(t.record(t.unknown)),
})

/** The hidden post's author, reduced to its DID. */
export interface BlockedAuthor {
  /** The author's DID. */
  did: string
  viewer?: ViewerState
}

export const BlockedAuthor: Codec<BlockedAuthor> = t.object({
  did: t.string,
  viewer: t.optional(ViewerState),
})

/** Hydrated external-link card (`app.bsky.embed.external#view`). */
export interface ExternalView {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.embed.external#view'
  external: ExternalLink
}

export const ExternalView: Codec<ExternalView> = t.object({
  $type: t.literal('app.bsky.embed.external#view'),
  external: ExternalLink,
})

/** A rich-text annotation over a byte range of `text` (`app.bsky.richtext.facet`): a mention, a link or a hashtag. */
export interface Facet {
  index: ByteSlice
  /** What the range is: one of `#mention` (`did`), `#link` (`uri`) or `#tag` (`tag`), each tagged by `$type`. */
  features: FacetFeature[]
}

export const Facet: Codec<Facet> = t.object({
  index: ByteSlice,
  features: t.array(FacetFeature),
})

/** One image with its CDN URLs. */
export interface ImageView {
  /** URL of the thumbnail. */
  thumb: string
  /** URL of the full-size image. */
  fullsize: string
  /** Alt text; empty when none was given. */
  alt: string
  aspectRatio?: AspectRatio
}

export const ImageView: Codec<ImageView> = t.object({
  thumb: t.string,
  fullsize: t.string,
  alt: t.string,
  aspectRatio: t.optional(AspectRatio),
})

/** A profile as listed in search results and follow graphs (`app.bsky.actor.defs#profileView`). */
export interface ProfileView {
  /** The account's DID, its permanent identifier. */
  did: string
  /** The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve. */
  handle: string
  /** Display name, when set. */
  displayName?: string
  /** URL of the avatar image, when set. */
  avatar?: string
  /** Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map. */
  associated?: Record<string, unknown>
  viewer?: ViewerState
  /** Moderation labels on the account. */
  labels?: Label[]
  /** When the account was created. */
  createdAt?: TimestampIso
  /** Profile bio, when set. */
  description?: string
  /** When the AppView last indexed the profile record. */
  indexedAt?: TimestampIso
}

export const ProfileView: Codec<ProfileView> = t.object({
  did: t.string,
  handle: t.string,
  displayName: t.optional(t.string),
  avatar: t.optional(t.string),
  associated: t.optional(t.record(t.unknown)),
  viewer: t.optional(ViewerState),
  labels: t.optional(t.array(Label)),
  createdAt: t.optional(t.dateTime),
  description: t.optional(t.string),
  indexedAt: t.optional(t.dateTime),
})

/** The smallest profile view, embedded as an author in posts (`app.bsky.actor.defs#profileViewBasic`). */
export interface ProfileViewBasic {
  /** The account's DID, its permanent identifier. */
  did: string
  /** The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve. */
  handle: string
  /** Display name, when set. */
  displayName?: string
  /** URL of the avatar image, when set. */
  avatar?: string
  /** Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map. */
  associated?: Record<string, unknown>
  viewer?: ViewerState
  /** Moderation labels on the account. */
  labels?: Label[]
  /** When the account was created. */
  createdAt?: TimestampIso
}

export const ProfileViewBasic: Codec<ProfileViewBasic> = t.object({
  did: t.string,
  handle: t.string,
  displayName: t.optional(t.string),
  avatar: t.optional(t.string),
  associated: t.optional(t.record(t.unknown)),
  viewer: t.optional(ViewerState),
  labels: t.optional(t.array(Label)),
  createdAt: t.optional(t.dateTime),
})

/** A full profile with counts (`app.bsky.actor.defs#profileViewDetailed`). */
export interface ProfileViewDetailed {
  /** The account's DID, its permanent identifier. */
  did: string
  /** The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve. */
  handle: string
  /** Display name, when set. */
  displayName?: string
  /** URL of the avatar image, when set. */
  avatar?: string
  /** Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map. */
  associated?: Record<string, unknown>
  viewer?: ViewerState
  /** Moderation labels on the account. */
  labels?: Label[]
  /** When the account was created. */
  createdAt?: TimestampIso
  /** Profile bio, when set. */
  description?: string
  /** URL of the banner image, when set. */
  banner?: string
  /** Number of accounts following this one. */
  followersCount?: number
  /** Number of accounts this one follows. */
  followsCount?: number
  /** Number of posts by this account. */
  postsCount?: number
  /** When the AppView last indexed the profile record. */
  indexedAt?: TimestampIso
  pinnedPost?: StrongRef
}

export const ProfileViewDetailed: Codec<ProfileViewDetailed> = t.object({
  did: t.string,
  handle: t.string,
  displayName: t.optional(t.string),
  avatar: t.optional(t.string),
  associated: t.optional(t.record(t.unknown)),
  viewer: t.optional(ViewerState),
  labels: t.optional(t.array(Label)),
  createdAt: t.optional(t.dateTime),
  description: t.optional(t.string),
  banner: t.optional(t.string),
  followersCount: t.optional(t.integer),
  followsCount: t.optional(t.integer),
  postsCount: t.optional(t.integer),
  indexedAt: t.optional(t.dateTime),
  pinnedPost: t.optional(StrongRef),
})

/** Which thread the post replies into, when it is a reply. */
export interface ReplyRef {
  root: StrongRef
  parent: StrongRef
}

export const ReplyRef: Codec<ReplyRef> = t.object({
  root: StrongRef,
  parent: StrongRef,
})

/** Hydrated video embed (`app.bsky.embed.video#view`). */
export interface VideoView {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.embed.video#view'
  /** CID of the video blob. */
  cid: string
  /** URL of the HLS playlist. */
  playlist: string
  /** URL of the poster image, when there is one. */
  thumbnail?: string
  /** Alt text, when given. */
  alt?: string
  aspectRatio?: AspectRatio
}

export const VideoView: Codec<VideoView> = t.object({
  $type: t.literal('app.bsky.embed.video#view'),
  cid: t.string,
  playlist: t.string,
  thumbnail: t.optional(t.string),
  alt: t.optional(t.string),
  aspectRatio: t.optional(AspectRatio),
})

/** A post hidden by a block between the viewer and its author (`app.bsky.feed.defs#blockedPost`). */
export interface BlockedPost {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#blockedPost'
  /** AT URI of the hidden post. */
  uri: string
  /** Always `true`. */
  blocked: true
  author: BlockedAuthor
}

export const BlockedPost: Codec<BlockedPost> = t.object({
  $type: t.literal('app.bsky.feed.defs#blockedPost'),
  uri: t.string,
  blocked: t.literal(true),
  author: BlockedAuthor,
})

/** Hydrated image embed (`app.bsky.embed.images#view`). */
export interface ImagesView {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.embed.images#view'
  /** The images, in order. */
  images: ImageView[]
}

export const ImagesView: Codec<ImagesView> = t.object({
  $type: t.literal('app.bsky.embed.images#view'),
  images: t.array(ImageView),
})

/** The post record as its author wrote it (`app.bsky.feed.post`). An open object: the fields declared here are the ones every post carries plus the common optional ones; a client may put more in. */
export interface PostRecord {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.post'
  /** The post text, at most 300 graphemes. */
  text: string
  /** When the author's client says the post was written. Client-supplied, unlike `indexedAt` on the view. */
  createdAt: TimestampIso
  /** BCP 47 language tags of the text, when the client set them. */
  langs?: string[]
  reply?: ReplyRef
  /** Rich-text annotations over `text`. */
  facets?: Facet[]
  embed?: RecordEmbed
  /** Additional hashtags, outside the text. */
  tags?: string[]
}

export const PostRecord: Codec<PostRecord> = t.object({
  $type: t.literal('app.bsky.feed.post'),
  text: t.string,
  createdAt: t.dateTime,
  langs: t.optional(t.array(t.string)),
  reply: t.optional(ReplyRef),
  facets: t.optional(t.array(Facet)),
  embed: t.optional(RecordEmbed),
  tags: t.optional(t.array(t.string)),
})

/** The post was reposted by `by` (`app.bsky.feed.defs#reasonRepost`). */
export interface ReasonRepost {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#reasonRepost'
  by: ProfileViewBasic
  /** When the repost was indexed. */
  indexedAt: TimestampIso
}

export const ReasonRepost: Codec<ReasonRepost> = t.object({
  $type: t.literal('app.bsky.feed.defs#reasonRepost'),
  by: ProfileViewBasic,
  indexedAt: t.dateTime,
})

/** A quote with media attached (`app.bsky.embed.recordWithMedia#view`). */
export interface RecordWithMediaView {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.embed.recordWithMedia#view'
  record: RecordView
  /** The attached media, tagged by `$type`. */
  media: ImagesView | ExternalView | VideoView
}

export const RecordWithMediaView: Codec<RecordWithMediaView> = t.object({
  $type: t.literal('app.bsky.embed.recordWithMedia#view'),
  record: RecordView,
  media: t.union(ImagesView, ExternalView, VideoView),
})

export type EmbedView = ImagesView | ExternalView | VideoView | RecordView | RecordWithMediaView | UnknownEmbedView

export const EmbedView: Codec<EmbedView> = t.union(ImagesView, ExternalView, VideoView, RecordView, RecordWithMediaView, UnknownEmbedView)

/** A post as the AppView serves it: the record plus its author, counts and hydrated embed (`app.bsky.feed.defs#postView`). */
export interface PostView {
  /** AT URI of the post. */
  uri: string
  /** CID of the post record version. */
  cid: string
  author: ProfileViewBasic
  record: PostRecord
  /** The hydrated embed of a post, tagged by `$type` (`app.bsky.embed.*#view`). The union is open: a tag none of the modelled members carries validates as `UnknownEmbedView` rather than failing the post. */
  embed?: ImagesView | ExternalView | VideoView | RecordView | RecordWithMediaView | UnknownEmbedView
  /** Number of replies. */
  replyCount?: number
  /** Number of reposts. */
  repostCount?: number
  /** Number of likes. */
  likeCount?: number
  /** Number of quote posts. */
  quoteCount?: number
  /** When the AppView indexed this version of the post. */
  indexedAt: TimestampIso
  /** The viewer's own like, repost and mute state on the post (`app.bsky.feed.defs#viewerState`). Kept as a map; empty without credentials. */
  viewer?: Record<string, unknown>
  /** Moderation labels on the post. */
  labels?: Label[]
  /** The thread's reply gate, when the root post has one (`app.bsky.feed.defs#threadgateView`). Kept as a map. */
  threadgate?: Record<string, unknown>
}

export const PostView: Codec<PostView> = t.object({
  uri: t.string,
  cid: t.string,
  author: ProfileViewBasic,
  record: PostRecord,
  embed: t.optional(t.union(ImagesView, ExternalView, VideoView, RecordView, RecordWithMediaView, UnknownEmbedView)),
  replyCount: t.optional(t.integer),
  repostCount: t.optional(t.integer),
  likeCount: t.optional(t.integer),
  quoteCount: t.optional(t.integer),
  indexedAt: t.dateTime,
  viewer: t.optional(t.record(t.unknown)),
  labels: t.optional(t.array(Label)),
  threadgate: t.optional(t.record(t.unknown)),
})

/** The thread context of a reply (`app.bsky.feed.defs#replyRef`). */
export interface FeedReplyRef {
  /** A post referenced from a reply chain: the post view, or a marker that it is gone or blocked. */
  root: PostView | NotFoundPost | BlockedPost
  /** A post referenced from a reply chain: the post view, or a marker that it is gone or blocked. */
  parent: PostView | NotFoundPost | BlockedPost
  grandparentAuthor?: ProfileViewBasic
}

export const FeedReplyRef: Codec<FeedReplyRef> = t.object({
  root: t.union(PostView, NotFoundPost, BlockedPost),
  parent: t.union(PostView, NotFoundPost, BlockedPost),
  grandparentAuthor: t.optional(ProfileViewBasic),
})

export type ReplyRefPost = PostView | NotFoundPost | BlockedPost

export const ReplyRefPost: Codec<ReplyRefPost> = t.union(PostView, NotFoundPost, BlockedPost)

/** A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`). */
export interface ThreadPostItemAnyOf0 {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#threadViewPost'
  post: PostView
}

export const ThreadPostItemAnyOf0: Codec<ThreadPostItemAnyOf0> = t.object({
  $type: t.literal('app.bsky.feed.defs#threadViewPost'),
  post: PostView,
})

/** A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`). */
export interface ThreadPostParentAnyOf0 {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#threadViewPost'
  post: PostView
}

export const ThreadPostParentAnyOf0: Codec<ThreadPostParentAnyOf0> = t.object({
  $type: t.literal('app.bsky.feed.defs#threadViewPost'),
  post: PostView,
})

/** A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`). */
export interface ThreadPostThreadNodeAnyOf0 {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#threadViewPost'
  post: PostView
}

export const ThreadPostThreadNodeAnyOf0: Codec<ThreadPostThreadNodeAnyOf0> = t.object({
  $type: t.literal('app.bsky.feed.defs#threadViewPost'),
  post: PostView,
})

/** One feed entry: a post, plus why it is in the feed (`app.bsky.feed.defs#feedViewPost`). */
export interface FeedViewPost {
  post: PostView
  reply?: FeedReplyRef
  /** Why the post is in the feed when it is not the author's own: a repost, or a pin. */
  reason?: ReasonRepost | ReasonPin
  /** Opaque context from the feed generator, to echo back in interaction reports. */
  feedContext?: string
}

export const FeedViewPost: Codec<FeedViewPost> = t.object({
  post: PostView,
  reply: t.optional(FeedReplyRef),
  reason: t.optional(t.union(ReasonRepost, ReasonPin)),
  feedContext: t.optional(t.string),
})

export type ThreadNode = ThreadPostThreadNodeAnyOf0 | NotFoundPost | BlockedPost

export const ThreadNode: Codec<ThreadNode> = t.union(ThreadPostThreadNodeAnyOf0, NotFoundPost, BlockedPost)

/** The requested post with its ancestors and replies (`app.bsky.feed.defs#threadViewPost`). */
export interface ThreadViewPost {
  /** Lexicon type tag of this object. */
  $type: 'app.bsky.feed.defs#threadViewPost'
  post: PostView
  /** A parent or reply in a thread: the post, or a marker that it is gone or blocked. Its own `parent` and `replies` are not typed here, so a validated thread keeps one level around the root; `validate=False` returns the whole tree. */
  parent?: ThreadPostParentAnyOf0 | NotFoundPost | BlockedPost
  /** Direct replies, when `depth` allowed them. */
  replies?: (ThreadPostItemAnyOf0 | NotFoundPost | BlockedPost)[]
  /** The thread's reply gate, when the root has one (`app.bsky.feed.defs#threadgateView`). Kept as a map. */
  threadgate?: Record<string, unknown>
}

export const ThreadViewPost: Codec<ThreadViewPost> = t.object({
  $type: t.literal('app.bsky.feed.defs#threadViewPost'),
  post: PostView,
  parent: t.optional(t.union(ThreadPostParentAnyOf0, NotFoundPost, BlockedPost)),
  replies: t.optional(t.array(t.union(ThreadPostItemAnyOf0, NotFoundPost, BlockedPost))),
  threadgate: t.optional(t.record(t.unknown)),
})
