//! Generated by truewire — do not edit by hand.
//!
//! Bluesky: profiles, feeds, threads, the social graph and handle resolution from the public AppView, plus the Jetstream firehose of repository events. No credentials needed.
//!
//! See <https://docs.bsky.app/docs/get-started>.

pub mod core;
pub mod meta;
pub mod types;

pub use truewire_core::CallOptions;
