# Generated by truewire — do not edit by hand.
from truewire_core import PaginatedResponse
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import FeedViewPost


class Request(TypedDict):
  """Whose feed, which posts, which page."""

  actor: str
  """Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`."""
  limit: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 50."""
  cursor: NotRequired[str]
  """Opaque page token from the previous response; omit for the first page."""
  filter: NotRequired[
    Literal[
      'posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads'
    ]
  ]
  """Which posts to include."""


class AuthorFeed(TypedDict):
  """One page of the feed."""

  cursor: NotRequired[str]
  """Token for the next page; absent on the last one."""
  feed: list[FeedViewPost]
  """Feed entries, newest first."""


class GetAuthorFeed(Endpoint):
  """An account's posts and reposts, newest first, paged by cursor."""

  @overload
  def get_author_feed_paged(
    self,
    *,
    actor: str,
    limit: int | None = None,
    filter: Literal[
      'posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads'
    ]
    | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, str]: ...
  @overload
  def get_author_feed_paged(
    self,
    *,
    actor: str,
    limit: int | None = None,
    filter: Literal[
      'posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads'
    ]
    | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[FeedViewPost, str]: ...
  def get_author_feed_paged(
    self,
    *,
    actor: str,
    limit: int | None = None,
    filter: Literal[
      'posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads'
    ]
    | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[FeedViewPost, str]:
    """An account's posts and reposts, newest first, paged by cursor.

    Paged variant of `get_author_feed`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      actor: Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
      limit: Rows per page. Range [1, 100]; defaults to 50.
      filter: Which posts to include.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed)
    """

    async def next(cursor: str) -> tuple[list[FeedViewPost], str | None]:
      response = await self.get_author_feed(
        actor=actor, limit=limit, filter=filter, cursor=(cursor or None), validate=validate
      )
      rows = response.get('feed')
      state = response.get('cursor')
      return rows or [], state or None

    return PaginatedResponse('', next)

  @overload
  async def get_author_feed(
    self,
    *,
    actor: str,
    limit: int | None = None,
    cursor: str | None = None,
    filter: Literal[
      'posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads'
    ]
    | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_author_feed(
    self,
    *,
    actor: str,
    limit: int | None = None,
    cursor: str | None = None,
    filter: Literal[
      'posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads'
    ]
    | None = None,
    validate: bool | None = None,
  ) -> AuthorFeed: ...
  async def get_author_feed(
    self,
    *,
    actor: str,
    limit: int | None = None,
    cursor: str | None = None,
    filter: Literal[
      'posts_with_replies', 'posts_no_replies', 'posts_with_media', 'posts_and_author_threads'
    ]
    | None = None,
    validate: bool | None = None,
  ) -> AuthorFeed:
    """An account's posts and reposts, newest first, paged by cursor.

    Args:
      actor: Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
      limit: Rows per page. Range [1, 100]; defaults to 50.
      cursor: Opaque page token from the previous response; omit for the first page.
      filter: Which posts to include.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed)
    """
    request: Request = Request(actor=actor)
    if limit is not None:
      request['limit'] = limit
    if cursor is not None:
      request['cursor'] = cursor
    if filter is not None:
      request['filter'] = filter
    return await self.request(
      request,
      method='GET',
      path='/xrpc/app.bsky.feed.getAuthorFeed',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=AuthorFeed,
    )
