# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from bluesky.core import Endpoint
from bluesky.schemas import BlockedPost, NotFoundPost, ThreadViewPost


class Request(TypedDict):
  """Which post and how much of its thread."""

  uri: str
  """AT URI of the post, such as `at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.feed.post/3kxyz...`."""
  depth: NotRequired[int]
  """How many levels of replies to include. Range [0, 1000]; defaults to 6."""
  parentHeight: NotRequired[int]
  """How many ancestors to include. Range [0, 1000]; defaults to 80."""


class PostThread(TypedDict):
  """The thread around the requested post."""

  thread: ThreadViewPost | NotFoundPost | BlockedPost
  """The requested post with its context, or a marker that it is gone or blocked."""
  threadgate: NotRequired[dict[str, Any]]
  """The thread's reply gate, when the root has one (`app.bsky.feed.defs#threadgateView`). Kept as a map."""


class GetPostThread(Endpoint):
  """A post with its ancestors and replies."""

  @overload
  async def get_post_thread(
    self,
    uri: str,
    *,
    depth: int | None = None,
    parent_height: int | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_post_thread(
    self,
    uri: str,
    *,
    depth: int | None = None,
    parent_height: int | None = None,
    validate: bool | None = None,
  ) -> PostThread: ...
  async def get_post_thread(
    self,
    uri: str,
    *,
    depth: int | None = None,
    parent_height: int | None = None,
    validate: bool | None = None,
  ) -> PostThread:
    """A post with its ancestors and replies.

    Args:
      uri: AT URI of the post, such as `at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.feed.post/3kxyz...`.
      depth: How many levels of replies to include. Range [0, 1000]; defaults to 6.
      parent_height: How many ancestors to include. Range [0, 1000]; defaults to 80.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-post-thread)
    """
    request: Request = Request(uri=uri)
    if depth is not None:
      request['depth'] = depth
    if parent_height is not None:
      request['parentHeight'] = parent_height
    return await self.request(
      request,
      method='GET',
      path='/xrpc/app.bsky.feed.getPostThread',
      meta={'public': True},
      validate=validate,
      request_type=Request,
      response_type=PostThread,
    )
