// Generated by truewire — do not edit by hand.
import type { CallOptions, StreamEndpoint, Subscription } from '@truewire/core'
import * as events from './events.js'

/**
 * Jetstream: Bluesky's JSON firehose of repository commits, identity changes and account status changes, over one WebSocket per subscription.
 *
 * @see https://github.com/bluesky-social/jetstream
 */
export class Jetstream {
  private readonly events_: events.Events

  constructor(readonly core: StreamEndpoint) {
    this.events_ = new events.Events(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  events(parameters: events.Parameters, options: CallOptions & { validate: false }): Subscription<unknown>
  /**
   * Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open.
   *
   * @see https://github.com/bluesky-social/jetstream#consuming-jetstream
   */
  events(parameters?: events.Parameters, options?: CallOptions): Subscription<events.JetstreamEvent>
  events(parameters?: events.Parameters, options?: CallOptions): Subscription<events.JetstreamEvent> {
    return this.events_.events(parameters, options)
  }
}
