// Generated by truewire — do not edit by hand.
import type { HttpEndpoint, StreamEndpoint } from '@truewire/core'
import { Actor } from './actor/index.js'
import { Feed } from './feed/index.js'
import { Graph } from './graph/index.js'
import { Identity } from './identity/index.js'
import { Jetstream } from './jetstream/index.js'
import type { DefaultMeta } from './meta.js'
import { Repo } from './repo/index.js'
import { Server } from './server/index.js'

/** The transports `Bluesky` is built from, one per field the composite's `truewire.toml` declarations name; the hand-written core satisfies it by shape. */
export interface BlueskyCore {
  client: HttpEndpoint<DefaultMeta>
  socket: StreamEndpoint
}

/**
 * Bluesky: profiles, feeds, threads, the social graph and handle resolution from the public AppView, plus the Jetstream firehose of repository events. No credentials needed.
 *
 * @see https://docs.bsky.app/docs/get-started
 */
export class Bluesky {
  /** Profiles: one, several, or by search (`app.bsky.actor.*`). */
  readonly actor: Actor
  /** Posts, threads and feeds (`app.bsky.feed.*`). */
  readonly feed: Feed
  /** The social graph: who follows whom (`app.bsky.graph.*`). */
  readonly graph: Graph
  /** Handle resolution (`com.atproto.identity.*`). */
  readonly identity: Identity
  /** Jetstream: Bluesky's JSON firehose of repository commits, identity changes and account status changes, over one WebSocket per subscription. */
  readonly jetstream: Jetstream
  /** Records in the account's own repository (`com.atproto.repo.*`): creating one and deleting it. A post is a record in the `app.bsky.feed.post` collection. */
  readonly repo: Repo
  /** Sessions (`com.atproto.server.*`): exchanging an app password for a session, and refreshing it. Everything else in this client is read-only and needs none of it. */
  readonly server: Server

  constructor(readonly core: BlueskyCore) {
    this.actor = new Actor(core.client)
    this.feed = new Feed(core.client)
    this.graph = new Graph(core.client)
    this.identity = new Identity(core.client)
    this.jetstream = new Jetstream(core.socket)
    this.repo = new Repo(core.client)
    this.server = new Server(core.client)
  }
}
