//! Generated by truewire — do not edit by hand.

use std::collections::HashMap;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::{BlockedPost, NotFoundPost, ThreadViewPost};

/// Which post and how much of its thread.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// AT URI of the post, such as `at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.feed.post/3kxyz...`.
    pub uri: String,
    /// How many levels of replies to include. Range [0, 1000]; defaults to 6.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    /// How many ancestors to include. Range [0, 1000]; defaults to 80.
    #[serde(
        rename = "parentHeight",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_height: Option<i64>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostThreadThread {
    ThreadViewPost(ThreadViewPost),
    NotFoundPost(NotFoundPost),
    BlockedPost(BlockedPost),
}

/// The thread around the requested post.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PostThread {
    /// The requested post with its context, or a marker that it is gone or blocked.
    pub thread: PostThreadThread,
    /// The thread's reply gate, when the root has one (`app.bsky.feed.defs#threadgateView`). Kept as a map.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub threadgate: Option<HashMap<String, serde_json::Value>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A post with its ancestors and replies.
#[derive(Clone)]
pub struct GetPostThread {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetPostThread {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// A post with its ancestors and replies.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-post-thread>.
    pub async fn get_post_thread(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<PostThread> {
        let raw = self.get_post_thread_raw(request, options).await?;
        decode(raw)
    }

    /// `get_post_thread` without validation: the wire body as it came.
    pub async fn get_post_thread_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(true),
            inject: None,
        };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.feed.getPostThread",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
