//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::paging::cursor_or_done;
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, PaginatedResponse, Result,
};

use crate::meta::DefaultMeta;
use crate::types::FeedViewPost;

/// Which feed and which page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// AT URI of the feed generator record (`app.bsky.feed.generator`).
    pub feed: String,
    /// Rows per page. Range [1, 100]; defaults to 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Opaque page token from the previous response; omit for the first page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One page of the feed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Feed {
    /// Token for the next page; absent on the last one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Feed entries, in the generator's order.
    pub feed: Vec<FeedViewPost>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `get_feed_paged`'s request: `Request` without `cursor`, which the walk advances.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetFeedPagedRequest {
    /// AT URI of the feed generator record (`app.bsky.feed.generator`).
    pub feed: String,
    /// Rows per page. Range [1, 100]; defaults to 50.
    pub limit: Option<i64>,
    /// Keys the spec does not document, sent as they are.
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl GetFeedPagedRequest {
    /// The `Request` for one page of the walk.
    fn at(&self, cursor: Option<String>) -> Request {
        Request {
            feed: self.feed.clone(),
            limit: self.limit,
            cursor,
            extra: self.extra.clone(),
        }
    }
}

/// A custom feed, served through its feed generator, paged by cursor.
#[derive(Clone)]
pub struct GetFeed {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetFeed {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// A custom feed, served through its feed generator, paged by cursor.
    ///
    /// Paged variant of `get_feed`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-feed>.
    pub fn get_feed_paged(
        &self,
        request: GetFeedPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<FeedViewPost, String> {
        let endpoint = self.clone();
        let next = move |cursor: String| {
            let endpoint = endpoint.clone();
            let request = request.clone();
            let options = options.clone();
            async move {
                let cursor = cursor_or_done(Some(cursor));
                let request = request.at(cursor);
                let response = endpoint.get_feed(request, options).await?;
                let cursor = response.cursor.clone();
                let rows = response.feed;
                Ok((rows, cursor_or_done(cursor)))
            }
        };
        PaginatedResponse::new(String::new(), next)
    }

    /// A custom feed, served through its feed generator, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-feed>.
    pub async fn get_feed(&self, request: Request, options: CallOptions) -> Result<Feed> {
        let raw = self.get_feed_raw(request, options).await?;
        decode(raw)
    }

    /// `get_feed` without validation: the wire body as it came.
    pub async fn get_feed_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { public: Some(true) };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.feed.getFeed",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
