//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::paging::cursor_or_done;
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, PaginatedResponse, Result,
};

use crate::meta::DefaultMeta;
use crate::types::FeedViewPost;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestFilter {
    #[serde(rename = "posts_with_replies")]
    PostsWithReplies,
    #[serde(rename = "posts_no_replies")]
    PostsNoReplies,
    #[serde(rename = "posts_with_media")]
    PostsWithMedia,
    #[serde(rename = "posts_and_author_threads")]
    PostsAndAuthorThreads,
}

/// Whose feed, which posts, which page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
    pub actor: String,
    /// Rows per page. Range [1, 100]; defaults to 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Opaque page token from the previous response; omit for the first page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Which posts to include.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<RequestFilter>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One page of the feed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthorFeed {
    /// Token for the next page; absent on the last one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Feed entries, newest first.
    pub feed: Vec<FeedViewPost>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `get_author_feed_paged`'s request: `Request` without `cursor`, which the walk advances.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetAuthorFeedPagedRequest {
    /// Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
    pub actor: String,
    /// Rows per page. Range [1, 100]; defaults to 50.
    pub limit: Option<i64>,
    /// Which posts to include.
    pub filter: Option<RequestFilter>,
    /// Keys the spec does not document, sent as they are.
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl GetAuthorFeedPagedRequest {
    /// The `Request` for one page of the walk.
    fn at(&self, cursor: Option<String>) -> Request {
        Request {
            actor: self.actor.clone(),
            limit: self.limit,
            cursor,
            filter: self.filter,
            extra: self.extra.clone(),
        }
    }
}

/// An account's posts and reposts, newest first, paged by cursor.
#[derive(Clone)]
pub struct GetAuthorFeed {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetAuthorFeed {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// An account's posts and reposts, newest first, paged by cursor.
    ///
    /// Paged variant of `get_author_feed`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed>.
    pub fn get_author_feed_paged(
        &self,
        request: GetAuthorFeedPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<FeedViewPost, String> {
        let endpoint = self.clone();
        let next = move |cursor: String| {
            let endpoint = endpoint.clone();
            let request = request.clone();
            let options = options.clone();
            async move {
                let cursor = cursor_or_done(Some(cursor));
                let request = request.at(cursor);
                let response = endpoint.get_author_feed(request, options).await?;
                let cursor = response.cursor.clone();
                let rows = response.feed;
                Ok((rows, cursor_or_done(cursor)))
            }
        };
        PaginatedResponse::new(String::new(), next)
    }

    /// An account's posts and reposts, newest first, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed>.
    pub async fn get_author_feed(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<AuthorFeed> {
        let raw = self.get_author_feed_raw(request, options).await?;
        decode(raw)
    }

    /// `get_author_feed` without validation: the wire body as it came.
    pub async fn get_author_feed_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { public: Some(true) };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.feed.getAuthorFeed",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
