//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::PostView;

/// Which posts.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// AT URIs of the posts, at most 25. Sent as repeated `uris` query parameters.
    pub uris: Vec<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The posts that exist, in the order asked for.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Posts {
    /// The posts.
    pub posts: Vec<PostView>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Get up to 25 posts by AT URI in one call.
#[derive(Clone)]
pub struct GetPosts {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetPosts {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Get up to 25 posts by AT URI in one call.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-posts>.
    pub async fn get_posts(&self, request: Request, options: CallOptions) -> Result<Posts> {
        let raw = self.get_posts_raw(request, options).await?;
        decode(raw)
    }

    /// `get_posts` without validation: the wire body as it came.
    pub async fn get_posts_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { public: Some(true) };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.feed.getPosts",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
