//! Generated by truewire — do not edit by hand.

pub mod get_author_feed;
pub mod get_feed;
pub mod get_post_thread;
pub mod get_posts;
pub mod search_posts;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, PaginatedResponse, Result};

use crate::meta::DefaultMeta;
use crate::types::{FeedViewPost, PostView};

/// Posts, threads and feeds (`app.bsky.feed.*`).
///
/// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed>.
#[derive(Clone)]
pub struct Feed {
    get_author_feed: get_author_feed::GetAuthorFeed,
    get_feed: get_feed::GetFeed,
    get_post_thread: get_post_thread::GetPostThread,
    get_posts: get_posts::GetPosts,
    search_posts: search_posts::SearchPosts,
}

impl Feed {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            get_author_feed: get_author_feed::GetAuthorFeed::new(core.clone()),
            get_feed: get_feed::GetFeed::new(core.clone()),
            get_post_thread: get_post_thread::GetPostThread::new(core.clone()),
            get_posts: get_posts::GetPosts::new(core.clone()),
            search_posts: search_posts::SearchPosts::new(core),
        }
    }

    /// An account's posts and reposts, newest first, paged by cursor.
    ///
    /// Paged variant of `get_author_feed`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed>.
    pub fn get_author_feed_paged(
        &self,
        request: get_author_feed::GetAuthorFeedPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<FeedViewPost, String> {
        self.get_author_feed.get_author_feed_paged(request, options)
    }

    /// An account's posts and reposts, newest first, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed>.
    pub async fn get_author_feed(
        &self,
        request: get_author_feed::Request,
        options: CallOptions,
    ) -> Result<get_author_feed::AuthorFeed> {
        self.get_author_feed.get_author_feed(request, options).await
    }

    /// `get_author_feed` without validation: the wire body as it came.
    pub async fn get_author_feed_raw(
        &self,
        request: get_author_feed::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_author_feed
            .get_author_feed_raw(request, options)
            .await
    }

    /// A custom feed, served through its feed generator, paged by cursor.
    ///
    /// Paged variant of `get_feed`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-feed>.
    pub fn get_feed_paged(
        &self,
        request: get_feed::GetFeedPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<FeedViewPost, String> {
        self.get_feed.get_feed_paged(request, options)
    }

    /// A custom feed, served through its feed generator, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-feed>.
    pub async fn get_feed(
        &self,
        request: get_feed::Request,
        options: CallOptions,
    ) -> Result<get_feed::Feed> {
        self.get_feed.get_feed(request, options).await
    }

    /// `get_feed` without validation: the wire body as it came.
    pub async fn get_feed_raw(
        &self,
        request: get_feed::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_feed.get_feed_raw(request, options).await
    }

    /// A post with its ancestors and replies.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-post-thread>.
    pub async fn get_post_thread(
        &self,
        request: get_post_thread::Request,
        options: CallOptions,
    ) -> Result<get_post_thread::PostThread> {
        self.get_post_thread.get_post_thread(request, options).await
    }

    /// `get_post_thread` without validation: the wire body as it came.
    pub async fn get_post_thread_raw(
        &self,
        request: get_post_thread::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_post_thread
            .get_post_thread_raw(request, options)
            .await
    }

    /// Get up to 25 posts by AT URI in one call.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-get-posts>.
    pub async fn get_posts(
        &self,
        request: get_posts::Request,
        options: CallOptions,
    ) -> Result<get_posts::Posts> {
        self.get_posts.get_posts(request, options).await
    }

    /// `get_posts` without validation: the wire body as it came.
    pub async fn get_posts_raw(
        &self,
        request: get_posts::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_posts.get_posts_raw(request, options).await
    }

    /// Full-text post search, paged by cursor.
    ///
    /// Paged variant of `search_posts`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-search-posts>.
    pub fn search_posts_paged(
        &self,
        request: search_posts::SearchPostsPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<PostView, String> {
        self.search_posts.search_posts_paged(request, options)
    }

    /// Full-text post search, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-search-posts>.
    pub async fn search_posts(
        &self,
        request: search_posts::Request,
        options: CallOptions,
    ) -> Result<search_posts::PostSearchResults> {
        self.search_posts.search_posts(request, options).await
    }

    /// `search_posts` without validation: the wire body as it came.
    pub async fn search_posts_raw(
        &self,
        request: search_posts::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.search_posts.search_posts_raw(request, options).await
    }
}
