//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::paging::cursor_or_done;
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, PaginatedResponse, Result,
};

use crate::meta::DefaultMeta;
use crate::types::PostView;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestSort {
    #[serde(rename = "top")]
    Top,
    #[serde(rename = "latest")]
    Latest,
}

/// The query, the order and the page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Search string. Lucene-style syntax is accepted.
    pub q: String,
    /// Result order.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort: Option<RequestSort>,
    /// Only posts by this account, as a handle or DID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    /// Only posts in this language, as a BCP 47 tag.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    /// Rows per page. Range [1, 100]; defaults to 25.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Opaque page token from the previous response; omit for the first page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One page of matching posts.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PostSearchResults {
    /// Token for the next page; absent on the last one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Approximate total number of matches, when the search backend reports one.
    #[serde(rename = "hitsTotal", default, skip_serializing_if = "Option::is_none")]
    pub hits_total: Option<i64>,
    /// Matching posts.
    pub posts: Vec<PostView>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `search_posts_paged`'s request: `Request` without `cursor`, which the walk advances.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchPostsPagedRequest {
    /// Search string. Lucene-style syntax is accepted.
    pub q: String,
    /// Result order.
    pub sort: Option<RequestSort>,
    /// Only posts by this account, as a handle or DID.
    pub author: Option<String>,
    /// Only posts in this language, as a BCP 47 tag.
    pub lang: Option<String>,
    /// Rows per page. Range [1, 100]; defaults to 25.
    pub limit: Option<i64>,
    /// Keys the spec does not document, sent as they are.
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl SearchPostsPagedRequest {
    /// The `Request` for one page of the walk.
    fn at(&self, cursor: Option<String>) -> Request {
        Request {
            q: self.q.clone(),
            sort: self.sort,
            author: self.author.clone(),
            lang: self.lang.clone(),
            limit: self.limit,
            cursor,
            extra: self.extra.clone(),
        }
    }
}

/// Full-text post search, paged by cursor.
#[derive(Clone)]
pub struct SearchPosts {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl SearchPosts {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Full-text post search, paged by cursor.
    ///
    /// Paged variant of `search_posts`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-search-posts>.
    pub fn search_posts_paged(
        &self,
        request: SearchPostsPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<PostView, String> {
        let endpoint = self.clone();
        let next = move |cursor: String| {
            let endpoint = endpoint.clone();
            let request = request.clone();
            let options = options.clone();
            async move {
                let cursor = cursor_or_done(Some(cursor));
                let request = request.at(cursor);
                let response = endpoint.search_posts(request, options).await?;
                let cursor = response.cursor.clone();
                let rows = response.posts;
                Ok((rows, cursor_or_done(cursor)))
            }
        };
        PaginatedResponse::new(String::new(), next)
    }

    /// Full-text post search, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-feed-search-posts>.
    pub async fn search_posts(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<PostSearchResults> {
        let raw = self.search_posts_raw(request, options).await?;
        decode(raw)
    }

    /// `search_posts` without validation: the wire body as it came.
    pub async fn search_posts_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(true),
            inject: None,
        };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.feed.searchPosts",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
