# Generated by truewire — do not edit by hand.
from .events import Events


class Jetstream(Events):
  """Jetstream: Bluesky's JSON firehose of repository commits, identity changes and account status changes, over one WebSocket per subscription.

  References:
    - [Upstream docs](https://github.com/bluesky-social/jetstream)
  """
