# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso, TimestampMicros
from truewire_core.util import StreamManager
from typing_extensions import Any, Literal, NotRequired, TypedDict
from bluesky.core import StreamEndpoint


class AccountStatus(TypedDict):
  """An account status change; present when `kind` is `account`."""

  active: bool
  """Whether the account is active on its host."""
  did: str
  """The account's DID."""
  seq: int
  """Sequence number on the upstream firehose."""
  time: TimestampIso
  """When the change happened."""
  status: NotRequired[str]
  """Why the account is inactive, when it is: `takendown`, `suspended`, `deleted` or `deactivated`."""


class Commit(TypedDict):
  """One record operation in the repository; present when `kind` is `commit`."""

  rev: str
  """Repository revision after this commit."""
  operation: Literal['create', 'update', 'delete']
  """What happened to the record."""
  collection: str
  """Collection NSID of the record, such as `app.bsky.feed.post`."""
  rkey: str
  """Record key within the collection."""
  record: NotRequired[dict[str, Any]]
  """The record, for `create` and `update`; absent on `delete`. Any collection's record, so kept as a map: `$type` names the lexicon."""
  cid: NotRequired[str]
  """CID of the record, for `create` and `update`; absent on `delete`."""


class Identity(TypedDict):
  """An identity change; present when `kind` is `identity`."""

  did: str
  """The DID whose identity changed."""
  handle: NotRequired[str]
  """The current handle, when it resolved."""
  seq: int
  """Sequence number on the upstream firehose."""
  time: TimestampIso
  """When the change happened."""


class Parameters(TypedDict):
  """The filter and the starting point, sent as the connection URL's query string."""

  wantedCollections: NotRequired[list[str]]
  """Collection NSIDs to include, such as `app.bsky.feed.post`; a trailing `.*` matches a prefix (`app.bsky.graph.*`). At most 100. Omit for every collection. Sent as repeated `wantedCollections` query parameters."""
  wantedDids: NotRequired[list[str]]
  """DIDs to include, at most 10000. Omit for every account. Sent as repeated `wantedDids` query parameters."""
  cursor: NotRequired[TimestampMicros]
  """Replay from this instant, as Unix microseconds on the wire; omit to start from now. Jetstream keeps a bounded backlog, and a cursor before it starts from the oldest event kept."""


class JetstreamEvent(TypedDict):
  """One event. `kind` says which of `commit`, `identity` and `account` is present."""

  did: str
  """DID of the repository the event is about."""
  time_us: TimestampMicros
  """When the event was emitted, as Unix microseconds on the wire. Also the cursor to resume from."""
  kind: Literal['commit', 'identity', 'account']
  """Event kind: a repository commit, an identity (handle or DID document) change, or an account status change."""
  commit: NotRequired[Commit]
  identity: NotRequired[Identity]
  account: NotRequired[AccountStatus]


class Events(StreamEndpoint):
  """Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open."""

  def events(
    self,
    *,
    wanted_collections: list[str] | None = None,
    wanted_dids: list[str] | None = None,
    cursor: TimestampMicros | None = None,
    validate: bool | None = None,
  ) -> StreamManager[JetstreamEvent, Any, Any]:
    """Subscribe to Jetstream: every repository commit, identity change and account status change on the network as JSON, filtered by collection and by account, from now or from a past cursor. One WebSocket connection per subscription; the parameters travel in the connection URL and the server starts pushing as soon as it is open.

    Args:
      wanted_collections: Collection NSIDs to include, such as `app.bsky.feed.post`; a trailing `.*` matches a prefix (`app.bsky.graph.*`). At most 100. Omit for every collection. Sent as repeated `wantedCollections` query parameters.
      wanted_dids: DIDs to include, at most 10000. Omit for every account. Sent as repeated `wantedDids` query parameters.
      cursor: Replay from this instant, as Unix microseconds on the wire; omit to start from now. Jetstream keeps a bounded backlog, and a cursor before it starts from the oldest event kept.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://github.com/bluesky-social/jetstream#consuming-jetstream)
    """
    parameters: Parameters = Parameters()
    if wanted_collections is not None:
      parameters['wantedCollections'] = wanted_collections
    if wanted_dids is not None:
      parameters['wantedDids'] = wanted_dids
    if cursor is not None:
      parameters['cursor'] = cursor
    return self.subscribe(
      'subscribe',
      parameters,
      validate=validate,
      request_type=Parameters,
      response_type=JetstreamEvent,
    )
