# Generated by truewire — do not edit by hand.
from functools import cached_property
from .actor import Actor
from .feed import Feed
from .graph import Graph
from .identity import Identity
from .jetstream import Jetstream
from .repo import Repo
from .server import Server
from bluesky.core import ClientBase


class Bluesky(ClientBase):
  """Bluesky: profiles, feeds, threads, the social graph and handle resolution from the public AppView, plus the Jetstream firehose of repository events. No credentials needed.

  References:
    - [Upstream docs](https://docs.bsky.app/docs/get-started)
  """

  @cached_property
  def actor(self) -> Actor:
    """Profiles: one, several, or by search (`app.bsky.actor.*`).

    References:
      - [Upstream docs](https://docs.bsky.app/docs/api/app-bsky-actor-get-profile)
    """
    return Actor(client=self.client)

  @cached_property
  def feed(self) -> Feed:
    """Posts, threads and feeds (`app.bsky.feed.*`).

    References:
      - [Upstream docs](https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed)
    """
    return Feed(client=self.client)

  @cached_property
  def graph(self) -> Graph:
    """The social graph: who follows whom (`app.bsky.graph.*`).

    References:
      - [Upstream docs](https://docs.bsky.app/docs/api/app-bsky-graph-get-followers)
    """
    return Graph(client=self.client)

  @cached_property
  def identity(self) -> Identity:
    """Handle resolution (`com.atproto.identity.*`).

    References:
      - [Upstream docs](https://docs.bsky.app/docs/api/com-atproto-identity-resolve-handle)
    """
    return Identity(client=self.client)

  @cached_property
  def jetstream(self) -> Jetstream:
    """Jetstream: Bluesky's JSON firehose of repository commits, identity changes and account status changes, over one WebSocket per subscription.

    References:
      - [Upstream docs](https://github.com/bluesky-social/jetstream)
    """
    return Jetstream(client=self.socket)

  @cached_property
  def repo(self) -> Repo:
    """Records in the account's own repository (`com.atproto.repo.*`): creating one and deleting it. A post is a record in the `app.bsky.feed.post` collection.

    References:
      - [Upstream docs](https://docs.bsky.app/docs/api/com-atproto-repo-create-record)
    """
    return Repo(client=self.client)

  @cached_property
  def server(self) -> Server:
    """Sessions (`com.atproto.server.*`): exchanging an app password for a session, and refreshing it. Everything else in this client is read-only and needs none of it.

    References:
      - [Upstream docs](https://docs.bsky.app/docs/api/com-atproto-server-create-session)
    """
    return Server(client=self.client)
