# Generated by truewire — do not edit by hand.
"""Shapes shared by two or more endpoints under the client root, generated from `spec/schemas.json`."""

from typing_extensions import Any, Literal, NotRequired, TypedDict
from truewire_core.types import TimestampIso


class AspectRatio(TypedDict):
  """Width and height of a media item, as a ratio."""

  width: int
  """Width."""
  height: int
  """Height."""


class ByteSlice(TypedDict):
  """The annotated byte range of `text`, UTF-8, end exclusive."""

  byteStart: int
  """First byte of the range."""
  byteEnd: int
  """Byte after the last byte of the range."""


class ExternalLink(TypedDict):
  """The link card."""

  uri: str
  """The linked URL."""
  title: str
  """Card title."""
  description: str
  """Card description."""
  thumb: NotRequired[str]
  """URL of the card image, when there is one."""


FacetFeatureKeywords = TypedDict('FacetFeatureKeywords', {'$type': str})
"""
- `$type`: Feature type: `app.bsky.richtext.facet#mention`, `#link` or `#tag`.
"""


class FacetFeature(FacetFeatureKeywords):
  """One feature, tagged by `$type`. The other fields depend on the tag and are kept as they came."""


class Label(TypedDict):
  """A moderation label applied to an account or a record (`com.atproto.label.defs#label`). Only the fields every label carries are declared."""

  ver: NotRequired[int]
  """Label schema version."""
  src: str
  """DID of the labeler that applied the label."""
  uri: str
  """AT URI of the labeled record, or the DID of the labeled account."""
  cid: NotRequired[str]
  """CID of the labeled record version, when the label is version-specific."""
  val: str
  """The label value, such as `porn` or `!hide`."""
  neg: NotRequired[bool]
  """Whether this label negates an earlier label with the same `src`, `uri` and `val`."""
  cts: TimestampIso
  """When the label was created."""
  exp: NotRequired[TimestampIso]
  """When the label expires, if it does."""


NotFoundPostKeywords = TypedDict(
  'NotFoundPostKeywords', {'$type': Literal['app.bsky.feed.defs#notFoundPost']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class NotFoundPost(NotFoundPostKeywords):
  """A post that does not exist or was deleted (`app.bsky.feed.defs#notFoundPost`)."""

  uri: str
  """AT URI that was asked for."""
  notFound: Literal[True]
  """Always `true`."""


ReasonPinKeywords = TypedDict(
  'ReasonPinKeywords', {'$type': Literal['app.bsky.feed.defs#reasonPin']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ReasonPin(ReasonPinKeywords):
  """The post is pinned to the profile (`app.bsky.feed.defs#reasonPin`)."""


RecordEmbedKeywords = TypedDict('RecordEmbedKeywords', {'$type': str})
"""
- `$type`: Embed type, such as `app.bsky.embed.images`.
"""


class RecordEmbed(RecordEmbedKeywords):
  """The embed as written in the record (images, external link, quoted record, video), tagged by `$type`. Kept as it came; the hydrated `embed` on the post view is the typed one."""


RecordViewKeywords = TypedDict(
  'RecordViewKeywords', {'$type': Literal['app.bsky.embed.record#view']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class RecordView(RecordViewKeywords):
  """Hydrated quote of another record (`app.bsky.embed.record#view`)."""

  record: dict[str, Any]
  """The quoted record's view, tagged by `$type`: a post (`#viewRecord`), a not-found, blocked or detached marker, or a feed generator, list, labeler or starter pack view. Kept as a map."""


class RepoCommit(TypedDict):
  """One commit to a repository: every write returns the commit that carried it, which is how a caller orders its own writes against the firehose."""

  cid: str
  """CID of the commit."""
  rev: str
  """Revision of the repository after it."""


class StrongRef(TypedDict):
  """A reference to a specific version of a record: its AT URI and the CID of that version (`com.atproto.repo.strongRef`)."""

  uri: str
  """AT URI of the record (`at://<did>/<collection>/<rkey>`)."""
  cid: str
  """CID of the referenced record version."""


UnknownEmbedViewKeywords = TypedDict('UnknownEmbedViewKeywords', {'$type': str})
"""
- `$type`: Embed type, such as `app.bsky.embed.gallery#view`.
"""


class UnknownEmbedView(UnknownEmbedViewKeywords):
  """An embed whose `$type` this spec does not model, kept so one unknown embed does not fail the page it arrived on (`app.bsky.embed.gallery#view` appeared in a feed while this client was being written). Only the tag survives validation; the payload is dropped, and `validate=False` returns it whole."""


class ViewerState(TypedDict):
  """The relationship between the authenticated viewer and this account (`app.bsky.actor.defs#viewerState`). Without credentials the public AppView sends an empty or absent object."""

  muted: NotRequired[bool]
  """Whether the viewer has muted this account."""
  mutedByList: NotRequired[dict[str, Any]]
  """The list through which the account is muted, when it is (`app.bsky.graph.defs#listViewBasic`). Kept as a map."""
  blockedBy: NotRequired[bool]
  """Whether this account blocks the viewer."""
  blocking: NotRequired[str]
  """AT URI of the viewer's block record against this account, when there is one."""
  blockingByList: NotRequired[dict[str, Any]]
  """The list through which the account is blocked, when it is (`app.bsky.graph.defs#listViewBasic`). Kept as a map."""
  following: NotRequired[str]
  """AT URI of the viewer's follow record for this account, when there is one."""
  followedBy: NotRequired[str]
  """AT URI of this account's follow record for the viewer, when there is one."""
  knownFollowers: NotRequired[dict[str, Any]]
  """Followers of this account the viewer also follows (`app.bsky.actor.defs#knownFollowers`). Kept as a map."""


class BlockedAuthor(TypedDict):
  """The hidden post's author, reduced to its DID."""

  did: str
  """The author's DID."""
  viewer: NotRequired[ViewerState]


ExternalViewKeywords = TypedDict(
  'ExternalViewKeywords', {'$type': Literal['app.bsky.embed.external#view']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ExternalView(ExternalViewKeywords):
  """Hydrated external-link card (`app.bsky.embed.external#view`)."""

  external: ExternalLink


class Facet(TypedDict):
  """A rich-text annotation over a byte range of `text` (`app.bsky.richtext.facet`): a mention, a link or a hashtag."""

  index: ByteSlice
  features: list[FacetFeature]
  """What the range is: one of `#mention` (`did`), `#link` (`uri`) or `#tag` (`tag`), each tagged by `$type`."""


class ImageView(TypedDict):
  """One image with its CDN URLs."""

  thumb: str
  """URL of the thumbnail."""
  fullsize: str
  """URL of the full-size image."""
  alt: str
  """Alt text; empty when none was given."""
  aspectRatio: NotRequired[AspectRatio]


class ProfileView(TypedDict):
  """A profile as listed in search results and follow graphs (`app.bsky.actor.defs#profileView`)."""

  did: str
  """The account's DID, its permanent identifier."""
  handle: str
  """The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve."""
  displayName: NotRequired[str]
  """Display name, when set."""
  avatar: NotRequired[str]
  """URL of the avatar image, when set."""
  associated: NotRequired[dict[str, Any]]
  """Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map."""
  viewer: NotRequired[ViewerState]
  labels: NotRequired[list[Label]]
  """Moderation labels on the account."""
  createdAt: NotRequired[TimestampIso]
  """When the account was created."""
  description: NotRequired[str]
  """Profile bio, when set."""
  indexedAt: NotRequired[TimestampIso]
  """When the AppView last indexed the profile record."""


class ProfileViewBasic(TypedDict):
  """The smallest profile view, embedded as an author in posts (`app.bsky.actor.defs#profileViewBasic`)."""

  did: str
  """The account's DID, its permanent identifier."""
  handle: str
  """The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve."""
  displayName: NotRequired[str]
  """Display name, when set."""
  avatar: NotRequired[str]
  """URL of the avatar image, when set."""
  associated: NotRequired[dict[str, Any]]
  """Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map."""
  viewer: NotRequired[ViewerState]
  labels: NotRequired[list[Label]]
  """Moderation labels on the account."""
  createdAt: NotRequired[TimestampIso]
  """When the account was created."""


class ProfileViewDetailed(TypedDict):
  """A full profile with counts (`app.bsky.actor.defs#profileViewDetailed`)."""

  did: str
  """The account's DID, its permanent identifier."""
  handle: str
  """The account's current handle, such as `bsky.app`; `handle.invalid` when it does not resolve."""
  displayName: NotRequired[str]
  """Display name, when set."""
  avatar: NotRequired[str]
  """URL of the avatar image, when set."""
  associated: NotRequired[dict[str, Any]]
  """Counts and flags for associated objects: lists, feed generators, starter packs, labeler and chat settings (`app.bsky.actor.defs#profileAssociated`). Kept as a map."""
  viewer: NotRequired[ViewerState]
  labels: NotRequired[list[Label]]
  """Moderation labels on the account."""
  createdAt: NotRequired[TimestampIso]
  """When the account was created."""
  description: NotRequired[str]
  """Profile bio, when set."""
  banner: NotRequired[str]
  """URL of the banner image, when set."""
  followersCount: NotRequired[int]
  """Number of accounts following this one."""
  followsCount: NotRequired[int]
  """Number of accounts this one follows."""
  postsCount: NotRequired[int]
  """Number of posts by this account."""
  indexedAt: NotRequired[TimestampIso]
  """When the AppView last indexed the profile record."""
  pinnedPost: NotRequired[StrongRef]


class ReplyRef(TypedDict):
  """Which thread the post replies into, when it is a reply."""

  root: StrongRef
  parent: StrongRef


VideoViewKeywords = TypedDict('VideoViewKeywords', {'$type': Literal['app.bsky.embed.video#view']})
"""
- `$type`: Lexicon type tag of this object.
"""


class VideoView(VideoViewKeywords):
  """Hydrated video embed (`app.bsky.embed.video#view`)."""

  cid: str
  """CID of the video blob."""
  playlist: str
  """URL of the HLS playlist."""
  thumbnail: NotRequired[str]
  """URL of the poster image, when there is one."""
  alt: NotRequired[str]
  """Alt text, when given."""
  aspectRatio: NotRequired[AspectRatio]


BlockedPostKeywords = TypedDict(
  'BlockedPostKeywords', {'$type': Literal['app.bsky.feed.defs#blockedPost']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class BlockedPost(BlockedPostKeywords):
  """A post hidden by a block between the viewer and its author (`app.bsky.feed.defs#blockedPost`)."""

  uri: str
  """AT URI of the hidden post."""
  blocked: Literal[True]
  """Always `true`."""
  author: BlockedAuthor


ImagesViewKeywords = TypedDict(
  'ImagesViewKeywords', {'$type': Literal['app.bsky.embed.images#view']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ImagesView(ImagesViewKeywords):
  """Hydrated image embed (`app.bsky.embed.images#view`)."""

  images: list[ImageView]
  """The images, in order."""


PostRecordKeywords = TypedDict('PostRecordKeywords', {'$type': Literal['app.bsky.feed.post']})
"""
- `$type`: Lexicon type tag of this object.
"""


class PostRecord(PostRecordKeywords):
  """The post record as its author wrote it (`app.bsky.feed.post`). An open object: the fields declared here are the ones every post carries plus the common optional ones; a client may put more in."""

  text: str
  """The post text, at most 300 graphemes."""
  createdAt: TimestampIso
  """When the author's client says the post was written. Client-supplied, unlike `indexedAt` on the view."""
  langs: NotRequired[list[str]]
  """BCP 47 language tags of the text, when the client set them."""
  reply: NotRequired[ReplyRef]
  facets: NotRequired[list[Facet]]
  """Rich-text annotations over `text`."""
  embed: NotRequired[RecordEmbed]
  tags: NotRequired[list[str]]
  """Additional hashtags, outside the text."""


ReasonRepostKeywords = TypedDict(
  'ReasonRepostKeywords', {'$type': Literal['app.bsky.feed.defs#reasonRepost']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ReasonRepost(ReasonRepostKeywords):
  """The post was reposted by `by` (`app.bsky.feed.defs#reasonRepost`)."""

  by: ProfileViewBasic
  indexedAt: TimestampIso
  """When the repost was indexed."""


RecordWithMediaViewKeywords = TypedDict(
  'RecordWithMediaViewKeywords', {'$type': Literal['app.bsky.embed.recordWithMedia#view']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class RecordWithMediaView(RecordWithMediaViewKeywords):
  """A quote with media attached (`app.bsky.embed.recordWithMedia#view`)."""

  record: RecordView
  media: ImagesView | ExternalView | VideoView
  """The attached media, tagged by `$type`."""


EmbedView = (
  ImagesView | ExternalView | VideoView | RecordView | RecordWithMediaView | UnknownEmbedView
)


class PostView(TypedDict):
  """A post as the AppView serves it: the record plus its author, counts and hydrated embed (`app.bsky.feed.defs#postView`)."""

  uri: str
  """AT URI of the post."""
  cid: str
  """CID of the post record version."""
  author: ProfileViewBasic
  record: PostRecord
  embed: NotRequired[
    ImagesView | ExternalView | VideoView | RecordView | RecordWithMediaView | UnknownEmbedView
  ]
  """The hydrated embed of a post, tagged by `$type` (`app.bsky.embed.*#view`). The union is open: a tag none of the modelled members carries validates as `UnknownEmbedView` rather than failing the post."""
  replyCount: NotRequired[int]
  """Number of replies."""
  repostCount: NotRequired[int]
  """Number of reposts."""
  likeCount: NotRequired[int]
  """Number of likes."""
  quoteCount: NotRequired[int]
  """Number of quote posts."""
  indexedAt: TimestampIso
  """When the AppView indexed this version of the post."""
  viewer: NotRequired[dict[str, Any]]
  """The viewer's own like, repost and mute state on the post (`app.bsky.feed.defs#viewerState`). Kept as a map; empty without credentials."""
  labels: NotRequired[list[Label]]
  """Moderation labels on the post."""
  threadgate: NotRequired[dict[str, Any]]
  """The thread's reply gate, when the root post has one (`app.bsky.feed.defs#threadgateView`). Kept as a map."""


class FeedReplyRef(TypedDict):
  """The thread context of a reply (`app.bsky.feed.defs#replyRef`)."""

  root: PostView | NotFoundPost | BlockedPost
  """A post referenced from a reply chain: the post view, or a marker that it is gone or blocked."""
  parent: PostView | NotFoundPost | BlockedPost
  """A post referenced from a reply chain: the post view, or a marker that it is gone or blocked."""
  grandparentAuthor: NotRequired[ProfileViewBasic]


ReplyRefPost = PostView | NotFoundPost | BlockedPost


ThreadPostItemAnyOf0Keywords = TypedDict(
  'ThreadPostItemAnyOf0Keywords', {'$type': Literal['app.bsky.feed.defs#threadViewPost']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ThreadPostItemAnyOf0(ThreadPostItemAnyOf0Keywords):
  """A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`)."""

  post: PostView


ThreadPostParentAnyOf0Keywords = TypedDict(
  'ThreadPostParentAnyOf0Keywords', {'$type': Literal['app.bsky.feed.defs#threadViewPost']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ThreadPostParentAnyOf0(ThreadPostParentAnyOf0Keywords):
  """A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`)."""

  post: PostView


ThreadPostThreadNodeAnyOf0Keywords = TypedDict(
  'ThreadPostThreadNodeAnyOf0Keywords', {'$type': Literal['app.bsky.feed.defs#threadViewPost']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ThreadPostThreadNodeAnyOf0(ThreadPostThreadNodeAnyOf0Keywords):
  """A post one level from the root (`app.bsky.feed.defs#threadViewPost`, without its own `parent`/`replies`)."""

  post: PostView


class FeedViewPost(TypedDict):
  """One feed entry: a post, plus why it is in the feed (`app.bsky.feed.defs#feedViewPost`)."""

  post: PostView
  reply: NotRequired[FeedReplyRef]
  reason: NotRequired[ReasonRepost | ReasonPin]
  """Why the post is in the feed when it is not the author's own: a repost, or a pin."""
  feedContext: NotRequired[str]
  """Opaque context from the feed generator, to echo back in interaction reports."""


ThreadNode = ThreadPostThreadNodeAnyOf0 | NotFoundPost | BlockedPost


ThreadViewPostKeywords = TypedDict(
  'ThreadViewPostKeywords', {'$type': Literal['app.bsky.feed.defs#threadViewPost']}
)
"""
- `$type`: Lexicon type tag of this object.
"""


class ThreadViewPost(ThreadViewPostKeywords):
  """The requested post with its ancestors and replies (`app.bsky.feed.defs#threadViewPost`)."""

  post: PostView
  parent: NotRequired[ThreadPostParentAnyOf0 | NotFoundPost | BlockedPost]
  """A parent or reply in a thread: the post, or a marker that it is gone or blocked. Its own `parent` and `replies` are not typed here, so a validated thread keeps one level around the root; `validate=False` returns the whole tree."""
  replies: NotRequired[list[ThreadPostItemAnyOf0 | NotFoundPost | BlockedPost]]
  """Direct replies, when `depth` allowed them."""
  threadgate: NotRequired[dict[str, Any]]
  """The thread's reply gate, when the root has one (`app.bsky.feed.defs#threadgateView`). Kept as a map."""
