//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::ProfileViewDetailed;

/// Which account.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Handle or DID of the account, such as `bsky.app` or `did:plc:z72i7hdynmk6r22z27h6tvur`.
    pub actor: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Get one account's full profile with follower, follow and post counts.
#[derive(Clone)]
pub struct GetProfile {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetProfile {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Get one account's full profile with follower, follow and post counts.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-get-profile>.
    pub async fn get_profile(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ProfileViewDetailed> {
        let raw = self.get_profile_raw(request, options).await?;
        decode(raw)
    }

    /// `get_profile` without validation: the wire body as it came.
    pub async fn get_profile_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { public: Some(true) };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.actor.getProfile",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
