//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::ProfileViewDetailed;

/// Which accounts.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Handles or DIDs, at most 25. Sent as repeated `actors` query parameters.
    pub actors: Vec<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The profiles, in the order asked for; an unresolvable actor is left out.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Profiles {
    /// The profiles.
    pub profiles: Vec<ProfileViewDetailed>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Get up to 25 full profiles in one call.
#[derive(Clone)]
pub struct GetProfiles {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetProfiles {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Get up to 25 full profiles in one call.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-get-profiles>.
    pub async fn get_profiles(&self, request: Request, options: CallOptions) -> Result<Profiles> {
        let raw = self.get_profiles_raw(request, options).await?;
        decode(raw)
    }

    /// `get_profiles` without validation: the wire body as it came.
    pub async fn get_profiles_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { public: Some(true) };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.actor.getProfiles",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
