//! Generated by truewire — do not edit by hand.

pub mod get_profile;
pub mod get_profiles;
pub mod search_actors;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, PaginatedResponse, Result};

use crate::meta::DefaultMeta;
use crate::types::{ProfileView, ProfileViewDetailed};

/// Profiles: one, several, or by search (`app.bsky.actor.*`).
///
/// See <https://docs.bsky.app/docs/api/app-bsky-actor-get-profile>.
#[derive(Clone)]
pub struct Actor {
    get_profile: get_profile::GetProfile,
    get_profiles: get_profiles::GetProfiles,
    search_actors: search_actors::SearchActors,
}

impl Actor {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            get_profile: get_profile::GetProfile::new(core.clone()),
            get_profiles: get_profiles::GetProfiles::new(core.clone()),
            search_actors: search_actors::SearchActors::new(core),
        }
    }

    /// Get one account's full profile with follower, follow and post counts.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-get-profile>.
    pub async fn get_profile(
        &self,
        request: get_profile::Request,
        options: CallOptions,
    ) -> Result<ProfileViewDetailed> {
        self.get_profile.get_profile(request, options).await
    }

    /// `get_profile` without validation: the wire body as it came.
    pub async fn get_profile_raw(
        &self,
        request: get_profile::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_profile.get_profile_raw(request, options).await
    }

    /// Get up to 25 full profiles in one call.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-get-profiles>.
    pub async fn get_profiles(
        &self,
        request: get_profiles::Request,
        options: CallOptions,
    ) -> Result<get_profiles::Profiles> {
        self.get_profiles.get_profiles(request, options).await
    }

    /// `get_profiles` without validation: the wire body as it came.
    pub async fn get_profiles_raw(
        &self,
        request: get_profiles::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_profiles.get_profiles_raw(request, options).await
    }

    /// Search accounts by name or handle, paged by cursor.
    ///
    /// Paged variant of `search_actors`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-search-actors>.
    pub fn search_actors_paged(
        &self,
        request: search_actors::SearchActorsPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<ProfileView, String> {
        self.search_actors.search_actors_paged(request, options)
    }

    /// Search accounts by name or handle, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-search-actors>.
    pub async fn search_actors(
        &self,
        request: search_actors::Request,
        options: CallOptions,
    ) -> Result<search_actors::ActorSearchResults> {
        self.search_actors.search_actors(request, options).await
    }

    /// `search_actors` without validation: the wire body as it came.
    pub async fn search_actors_raw(
        &self,
        request: search_actors::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.search_actors.search_actors_raw(request, options).await
    }
}
