//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::paging::cursor_or_done;
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, PaginatedResponse, Result,
};

use crate::meta::DefaultMeta;
use crate::types::ProfileView;

/// The query and the page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Search string, matched against handles, display names and bios.
    pub q: String,
    /// Rows per page. Range [1, 100]; defaults to 25.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Opaque page token from the previous response; omit for the first page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One page of matching profiles.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ActorSearchResults {
    /// Token for the next page; absent on the last one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Matching profiles, best first.
    pub actors: Vec<ProfileView>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `search_actors_paged`'s request: `Request` without `cursor`, which the walk advances.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SearchActorsPagedRequest {
    /// Search string, matched against handles, display names and bios.
    pub q: String,
    /// Rows per page. Range [1, 100]; defaults to 25.
    pub limit: Option<i64>,
    /// Keys the spec does not document, sent as they are.
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl SearchActorsPagedRequest {
    /// The `Request` for one page of the walk.
    fn at(&self, cursor: Option<String>) -> Request {
        Request {
            q: self.q.clone(),
            limit: self.limit,
            cursor,
            extra: self.extra.clone(),
        }
    }
}

/// Search accounts by name or handle, paged by cursor.
#[derive(Clone)]
pub struct SearchActors {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl SearchActors {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Search accounts by name or handle, paged by cursor.
    ///
    /// Paged variant of `search_actors`: await it for every row, or walk `rows()`/`pages()` one page at a time.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-search-actors>.
    pub fn search_actors_paged(
        &self,
        request: SearchActorsPagedRequest,
        options: CallOptions,
    ) -> PaginatedResponse<ProfileView, String> {
        let endpoint = self.clone();
        let next = move |cursor: String| {
            let endpoint = endpoint.clone();
            let request = request.clone();
            let options = options.clone();
            async move {
                let cursor = cursor_or_done(Some(cursor));
                let request = request.at(cursor);
                let response = endpoint.search_actors(request, options).await?;
                let cursor = response.cursor.clone();
                let rows = response.actors;
                Ok((rows, cursor_or_done(cursor)))
            }
        };
        PaginatedResponse::new(String::new(), next)
    }

    /// Search accounts by name or handle, paged by cursor.
    ///
    /// See <https://docs.bsky.app/docs/api/app-bsky-actor-search-actors>.
    pub async fn search_actors(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ActorSearchResults> {
        let raw = self.search_actors_raw(request, options).await?;
        decode(raw)
    }

    /// `search_actors` without validation: the wire body as it came.
    pub async fn search_actors_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            public: Some(true),
            inject: None,
        };
        let call = HttpCall {
            method: Some("GET"),
            path: "/xrpc/app.bsky.actor.searchActors",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
